### ISSUE TITLE
MS-LDAP : /LdapConnection.php:757 with message: LDAP query ... failed. Error: Operations error

### ISSUE THREAD

**Issue by linuxmail** [Icinga/icingaweb2#2802]
hi,

I installed icingaweb2 via Debian Jessie packages:

```
ii  icingaweb2                           2.4.1-1~debmon8+1         all          simple and responsive web interface for Icinga
ii  icingaweb2-common                    2.4.1-1~debmon8+1         all          simple and responsive web interface for Icinga - common files
ii  icingaweb2-module-doc                2.4.1-1~debmon8+1         all          simple and responsive web interface for Icinga - documentation module
ii  icingaweb2-module-monitoring         2.4.1-1~debmon8+1         all          simple and responsive web interface for Icinga - monitoring module
```

and DB auth etc. works. Now I tried to get AD auth working, but it fails in nearly all combinations, that works with ldapsearch.

```
icingaweb2[3817]: Icinga\Exception\AuthenticationException in /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php:393 with message: Failed to authenticate user "foobar" against backend "icingaweb". An exception was thrown: <- Icinga\Protocol\Ldap\LdapException in /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php:757 with message: LDAP query "(&(objectClass=user)(sAMAccountName=foobar))" (base DC=domain,DC=local) failed. Error: Operations error
```

The ldap search works:

 ```ldapsearch -x -h 192.168.1.1  -W -b "DC=domain,DC=local" -D "domain\icinga" '(&(!(objectClass=computer))(&(objectClass=user)(sAMAccountName=foobar)))' ```

 The added AD resource works, but it fails on verification in the authentication module.

```
Connect without encryption
LDAP bind to 192.168.1.1:389 ( / ***) successful
Microsoft Active Directory
Windows Server 2008 R2 (or newer)
Supports STARTTLS: True
Default naming context: DC=domain,DC=local
LDAP query "(&(!(objectClass=computer))(objectClass=user))" (base DC=domain,DC=local) failed. Error: Operations error
```
If I want list the users:

```
#0 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(416): Icinga\Protocol\Ldap\LdapConnection->runQuery(Object(Icinga\Protocol\Ldap\LdapQuery), NULL)
#1 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(433): Icinga\Protocol\Ldap\LdapConnection->fetchAll(Object(Icinga\Protocol\Ldap\LdapQuery), NULL)
#2 /usr/share/php/Icinga/Data/SimpleQuery.php(577): Icinga\Protocol\Ldap\LdapConnection->fetchRow(Object(Icinga\Protocol\Ldap\LdapQuery))
#3 /usr/share/php/Icinga/Data/SimpleQuery.php(453): Icinga\Data\SimpleQuery->fetchRow()
#4 /usr/share/php/Icinga/Repository/RepositoryQuery.php(450): Icinga\Data\SimpleQuery->hasResult()
#5 zend.view:///usr/share/icingaweb2/application/views/scripts/user/list.phtml(43): Icinga\Repository\RepositoryQuery->hasResult()
#6 /usr/share/php/Icinga/Web/View.php(231): include('zend.view:///us...')
#7 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render('user/list.phtml')
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('user/list.phtml', NULL)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('listAction')
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#18 {main}
```

Any suggestions?

cu denny

**Comment by lippserd** [comment]
Hi,

Sorry for the late response. If you still have problems, please open a new issue with the relevant log lines from your AD server. I think there's an issue with your filter.

Best regards,
Eric
