### ISSUE TITLE
Password is logged in cleartext when ldap_start_tls fails

### ISSUE THREAD

**Issue by zearan** [Icinga/icingaweb2#2810]
When ldap_start_tls() fails, the following log entry appears in the application log. In two lines the cleartext password of the user is logged. If stacktraces are enabled, the password is also shown on the error screen of the user.

```
ErrorException in /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php:1177 with message: ldap_start_tls(): Unable to start TLS: Connect error
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'ldap_start_tls(...', '/usr/share/php/...', 1177, Array)
#1 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(1177): ldap_start_tls(Resource id #184)
#2 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(235): Icinga\Protocol\Ldap\LdapConnection->prepareNewConnection()
#3 /usr/share/php/Icinga/Protocol/Ldap/LdapCapabilities.php(273): Icinga\Protocol\Ldap\LdapConnection->getConnection()
#4 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(250): Icinga\Protocol\Ldap\LdapCapabilities::discoverCapabilities(Object(Icinga\Protocol\Ldap\LdapConnection))
#5 /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php(224): Icinga\Protocol\Ldap\LdapConnection->getCapabilities()
#6 /usr/share/php/Icinga/Repository/Repository.php(345): Icinga\Authentication\User\LdapUserBackend->initializeQueryColumns()
#7 /usr/share/php/Icinga/Repository/Repository.php(298): Icinga\Repository\Repository->getQueryColumns()
#8 /usr/share/php/Icinga/Repository/Repository.php(703): Icinga\Repository\Repository->getBaseTable()
#9 /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php(377): Icinga\Repository\Repository->select()
#10 /usr/share/php/Icinga/Authentication/AuthChain.php(114): Icinga\Authentication\User\LdapUserBackend->authenticate(Object(Icinga\User), '<PASSWORD>')
#11 /usr/share/icingaweb2/application/forms/Authentication/LoginForm.php(91): Icinga\Authentication\AuthChain->authenticate(Object(Icinga\User), '<PASSWORD>')
#12 /usr/share/php/Icinga/Web/Form.php(1152): Icinga\Forms\Authentication\LoginForm->onSuccess()
#13 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(50): Icinga\Web\Form->handleRequest()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('loginAction')
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#20 {main}
```

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Yep, we should fix that.

Best regards,
Eric

**Comment by lippserd** [comment]
@Al2Klimov This is not only related to our authenticate function but all functions which accept confidential information, e.g. `PDO::__construct()`.

@Thomas-Gelf Should we implement our own `getTraceAsString()` function and not log any parameter? This may have an impact for debugging though. Any other thoughts?

**Comment by lippserd** [comment]
Discussed this with @Al2Klimov and we both think that it is best to write a custom "renderer" for stack traces and only show the parameter types. PHP's default renders the values of scalar types.
