### ISSUE TITLE
Permission denied in webui

### ISSUE THREAD

**Issue by djtecha** [Icinga/icingaweb2#2813]
When I try to write any command to the local /var/run/icinga2/cmd/icinga2.cmd I get permission denied.

Nginx is running as nobody:

```root     25852     1  0 12:47 ?        00:00:00 nginx: master process /platform/nginx/sbin/nginx
nobody   25853 25852  0 12:47 ?        00:00:00 nginx: worker process
```

Nobody Permissions:

```PROD# id nobody
uid=99(nobody) gid=99(nobody) groups=99(nobody),497(icingacmd),496(icingaweb2)
```

```PROD# ls -l /var/run/icinga2/cmd/icinga2.cmd
prw-rw---- 1 icinga icingacmd 0 Apr  7 17:04 /var/run/icinga2/cmd/icinga2.cmd
```

```icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.3)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.10.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```

Error I get when trying to write a comment:
```icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.

#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/AddCommentCommandForm.php(83): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\AddCommentCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1152): Icinga\Module\Monitoring\Forms\Command\Object\AddCommentCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(129): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostController.php(131): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->handleCommandForm(Object(Icinga\Module\Monitoring\Forms\Command\Object\AddCommentCommandForm))
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostController->addCommentAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('addCommentActio...')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```

I Tested write permissions too:

```
PROD# su -s /bin/bash icinga -c 'test -w /var/run/icinga2/cmd/icinga2.cmd' && echo $?
0
```

**Comment by leeclemens** [comment]
Did you mean to test with: `su -s /bin/bash nobody -c 'test -w /var/run/icinga2/cmd/icinga2.cmd' && echo $?` ?   Are you using php-fpm (what is executing php)?

There's a lot going on here that may be specific to your setup and you may get more responses from the mailing list.

**Comment by djtecha** [comment]
yes, it's using php-fpm 

```root     32533     1  0 Apr05 ?        00:00:51 php-fpm: master process (/etc/php-fpm.conf)
nobody   32535 32533  0 Apr05 ?        00:02:12 php-fpm: pool www
```
and that check confirms that it has write permissions. I can also echo anything to it really as that user.

**Comment by djtecha** [comment]
Ok, my bad. Looks like php-fpm needed a restart.
