### ISSUE TITLE
ldap authentication can't handle two server configured in resource

### ISSUE THREAD

**Issue by hannibal87** [Icinga/icingaweb2#2818]
The LDAP Authentication Plugin can't handle two server configured in the resource.ini. When only one server is configured the login works like a charm.
I think here is no separation for the two server. (As documented in04-Resources.md they have to be separated by space) 

authentication.ini:
[auth_ldap]
backend             = ldap
resource            = freeipa
user_class          = inetorgperson
user_name_attribute = uid
filter              = "memberOf=cn=test-group,dc=www,dc=example=org"

resources.ini:
[freeipa]
type        = ldap
hostname    = server1.example.org server2.example.org
port        = 389
root_dn     = "dc=www,dc=example,dc=org"
bind_dn     = "user"
bind_pw     = thisisnopassword

Error-Message: 
```
ldap_connect(): Could not create session handle: Bad parameter to an ldap routine

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'ldap_connect():...', '/usr/share/php/...', 1164, Array)
#1 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(1164): ldap_connect('server1.example...', '389')
#2 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(235): Icinga\Protocol\Ldap\LdapConnection->prepareNewConnection()
#3 /usr/share/php/Icinga/Protocol/Ldap/LdapCapabilities.php(273): Icinga\Protocol\Ldap\LdapConnection->getConnection()
#4 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(250): Icinga\Protocol\Ldap\LdapCapabilities::discoverCapabilities(Object(Icinga\Protocol\Ldap\LdapConnection))
#5 /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php(224): Icinga\Protocol\Ldap\LdapConnection->getCapabilities()
#6 /usr/share/php/Icinga/Repository/Repository.php(345): Icinga\Authentication\User\LdapUserBackend->initializeQueryColumns()
#7 /usr/share/php/Icinga/Repository/Repository.php(298): Icinga\Repository\Repository->getQueryColumns()
#8 /usr/share/php/Icinga/Repository/Repository.php(703): Icinga\Repository\Repository->getBaseTable()
#9 /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php(377): Icinga\Repository\Repository->select()
#10 /usr/share/php/Icinga/Authentication/AuthChain.php(114): Icinga\Authentication\User\LdapUserBackend->authenticate(Object(Icinga\User), 'bbb')
#11 /usr/share/icingaweb2/application/forms/Authentication/LoginForm.php(91): Icinga\Authentication\AuthChain->authenticate(Object(Icinga\User), 'bbb')
#12 /usr/share/php/Icinga/Web/Form.php(1152): Icinga\Forms\Authentication\LoginForm->onSuccess()
#13 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(50): Icinga\Web\Form->handleRequest()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('loginAction')
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#20 {main}
```

**Comment by ClemensBW** [comment]
Hello,

works for my setup:

`hostname = "ldaps://XXX.com ldaps://YYY.com"`

**Comment by lippserd** [comment]
Hi,

You should add quotes to the INI values. If the issue is still present, please open a new issue.

Best regards,
Eric

**Comment by hristoz** [comment]
Hi,

Where did you find the LDAP authentication logs?
Thanks.
