### ISSUE TITLE
Can't progress in wizard due to TransportConfigForm.php error

### ISSUE THREAD

**Issue by mamiral** [Icinga/icingaweb2#2842]
This is an error I get in setup wizard:

> Fatal error: Call to a member function setDecorators() on a non-object in ...//...modules/monitoring/application/forms/Config/TransportConfigForm.php on line 274 

This happens on cloned repo from github. But if I make yum install icingaweb2 it works. I have made diff on two files and although .spec file in icingaweb2 directory says same version of icingaweb2 (2.4.1) in repo and github clone, the file from yum repo is cca. 100 lines shorter! Is this some kind of bug or a misconfig on my side?

Here is the diff:
```
diff modules/monitoring/application/forms/Config/TransportConfigForm.php modules.working/monitoring/application/forms/Config/TransportConfigForm.php 
6,8d5
< use Icinga\Data\ConfigObject;
< use Icinga\Module\Monitoring\Command\Transport\CommandTransport;
< use Icinga\Module\Monitoring\Exception\CommandTransportException;
10d6
< use Icinga\Application\Platform;
41,45d36
<      * @var bool
<      */
<     protected $validatePartial = true;
< 
<     /**
91c82
<             case RemoteCommandFile::TRANSPORT:
---
>             case RemoteCommandFile::TRANSPORT;
232d222
<             ApiCommandTransport::TRANSPORT  => $this->translate('Icinga 2 API'),
234c224,225
<             RemoteCommandFile::TRANSPORT    => $this->translate('Remote Command File')
---
>             RemoteCommandFile::TRANSPORT    => $this->translate('Remote Command File'),
>             ApiCommandTransport::TRANSPORT  => $this->translate('Icinga 2 API')
236,238d226
<         if (! Platform::extensionLoaded('curl')) {
<             unset($transportTypes[ApiCommandTransport::TRANSPORT]);
<         }
262,314d249
<      * Add a submit button to this form and one to manually validate the configuration
<      *
<      * Calls parent::addSubmitButton() to add the submit button.
<      *
<      * @return  $this
<      */
<     public function addSubmitButton()
<     {
<         parent::addSubmitButton();
< 
<         if ($this->getSubForm('transport_form') instanceof ApiTransportForm) {
<             $this->getElement('btn_submit')
<                 ->setDecorators(array('ViewHelper'));
< 
<             $this->addElement(
<                 'submit',
<                 'transport_validation',
<                 array(
<                     'ignore' => true,
<                     'label' => $this->translate('Validate Configuration'),
<                     'data-progress-label' => $this->translate('Validation In Progress'),
<                     'decorators' => array('ViewHelper')
<                 )
<             );
< 
<             $this->setAttrib('data-progress-element', 'transport-progress');
<             $this->addElement(
<                 'note',
<                 'transport-progress',
<                 array(
<                     'decorators' => array(
<                         'ViewHelper',
<                         array('Spinner', array('id' => 'transport-progress'))
<                     )
<                 )
<             );
< 
<             $this->addDisplayGroup(
<                 array('btn_submit', 'transport_validation', 'transport-progress'),
<                 'submit_validation',
<                 array(
<                     'decorators' => array(
<                         'FormElements',
<                         array('HtmlTag', array('tag' => 'div', 'class' => 'control-group form-controls'))
<                     )
<                 )
<             );
<         }
< 
<         return $this;
<     }
< 
<     /**
325,377d259
< 
<     /**
<      * {@inheritdoc}
<      */
<     public function isValidPartial(array $formData)
<     {
<         $isValidPartial =  parent::isValidPartial($formData);
< 
<         $transportValidation = $this->getElement('transport_validation');
<         if ($transportValidation !== null && $transportValidation->isChecked() && $this->isValid($formData)) {
<             $this->info($this->translate('The configuration has been successfully validated.'));
<         }
< 
<         return $isValidPartial;
<     }
< 
<     /**
<      * {@inheritdoc}
<      */
<     public function isValid($formData)
<     {
<         if (! parent::isValid($formData)) {
<             return false;
<         }
< 
<         if (! ($this->getElement('transport_validation') === null || (
<             $this->isSubmitted() && isset($formData['force_creation']) && $formData['force_creation'])
<         )) {
<             try {
<                 CommandTransport::createTransport(new ConfigObject($this->getValues()))->probe();
<             } catch (CommandTransportException $e) {
<                 $this->error(sprintf(
<                     $this->translate('Failed to successfully validate the configuration: %s'),
<                     $e->getMessage()
<                 ));
< 
<                 $this->addElement(
<                     'checkbox',
<                     'force_creation',
<                     array(
<                         'order'         => 0,
<                         'ignore'        => true,
<                         'label'         => $this->translate('Force Changes'),
<                         'description'   => $this->translate('Check this box to enforce changes without connectivity validation')
<                     )
<                 );
< 
<                 return false;
<             }
<         }
< 
<         return true;
<     }

```

**Comment by Entrio** [comment]
I have the same issue, cloned the repo, setup host and php. Once I got to the point of entering IDO information, i did that clicked next and got the fatal error. Now my setup page doesnt work at all and keeps throwing up the error.
`Fatal error: Uncaught Error: Call to a member function setDecorators() on null in /var/www/icingaweb2/modules/monitoring/application/forms/Config/TransportConfigForm.php:274 Stack trace: #0 /var/www/icingaweb2/library/Icinga/Web/Form.php(775): Icinga\Module\Monitoring\Forms\Config\TransportConfigForm->addSubmitButton() #1 /var/www/icingaweb2/modules/monitoring/application/forms/Setup/TransportPage.php(24): Icinga\Web\Form->create(Array) #2 /var/www/icingaweb2/library/Icinga/Web/Form.php(772): Icinga\Module\Monitoring\Forms\Setup\TransportPage->createElements(Array) #3 /var/www/icingaweb2/library/Icinga/Web/Wizard.php(704): Icinga\Web\Form->create() #4 zend.view:///var/www/icingaweb2/modules/setup/application/views/scripts/index/parts/wizard.phtml(1): Icinga\Web\Wizard->getForm() #5 /var/www/icingaweb2/library/Icinga/Web/View.php(231): include('zend.view:///va...') #6 /var/www/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/var/www/icinga...') #7 zend.view:///var/www/icingaweb2/modules/setup/ in /var/www/icingaweb2/modules/monitoring/application/forms/Config/TransportConfigForm.php on line 274`

Nginx 1.6.2
php-fpm 7.1

**Comment by mamiral** [comment]
I have resolved this by using the **release** zip. Guess master branch is broken atm.

**Comment by NielsH** [comment]
The latest release currently also has this issue. I can confirm that the patch works. Would be great if it could be merged.
https://github.com/Icinga/icingaweb2/pull/2855/commits/828b3e5b3925935c7b05f2296d4cf3a63774afdb
