### ISSUE TITLE
Resource keeps disappearing

### ISSUE THREAD

**Issue by d-zalewski** [Icinga/icingaweb2#2892]
Hi,

I got mysql ido resource configured in my icingaweb2 and it keeps disappearing randomly. Another resource for icingaweb2 database on the same mysql server is fine.

icingaweb2 2.4.1
php-7.0.21
icinga2 2.6.3 on RHEL 7.3

```
2017-07-19T13:33:21+01:00 - ERROR - Could not invoke custom navigation item renderer. ErrorException in /usr/share/php/Icinga/Web/Navigation/Renderer/SummaryNavigationItemRenderer.php:58 with message: Undefined index:
2017-07-19T13:33:25+01:00 - ERROR - Could not invoke custom navigation item renderer. ErrorException in /usr/share/php/Icinga/Web/Navigation/Renderer/SummaryNavigationItemRenderer.php:58 with message: Undefined index:
2017-07-19T13:33:27+01:00 - ERROR - Could not invoke custom navigation item renderer. ErrorException in /usr/share/php/Icinga/Web/Navigation/Renderer/SummaryNavigationItemRenderer.php:58 with message: Undefined index:
2017-07-19T13:33:28+01:00 - ERROR - Icinga\Exception\ConfigurationError in /usr/share/php/Icinga/Data/ResourceFactory.php:50 with message: Cannot load resource config "mysql-ido". Resource does not exist
#0 /usr/share/php/Icinga/Data/ResourceFactory.php(140): Icinga\Data\ResourceFactory::getResourceConfig('mysql-ido')
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(230): Icinga\Data\ResourceFactory::create('mysql-ido')
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(305): Icinga\Module\Monitoring\Backend\MonitoringBackend->getResource()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(53): Icinga\Module\Monitoring\Backend\MonitoringBackend->query('ServiceStatus', Array)
#4 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(260): Icinga\Module\Monitoring\DataView\DataView->__construct(Object(Icinga\Module\Monitoring\Backend\Ido\IdoBackend), Array)
#5 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(161): Icinga\Module\Monitoring\Backend\MonitoringBackend->from('servicestatus', Array)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ListController->servicesAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('servicesAction')
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#12 {main}
```

**Comment by lippserd** [comment]
Hi,

Is your configuration managed by Puppet, Ansible or something like that?

**Comment by d-zalewski** [comment]
indeed it was puppet!
