### ISSUE TITLE
No such object available

### ISSUE THREAD

**Issue by darmagan** [Icinga/icingaweb2#3032]
In the roles if the director hostgroup filter is set, the respective user can't see or edit hosts anymore.

## Expected Behavior
The expected result with these permissions would be the limited user can add and edit hosts in the given HostGroups.

## Current Behavior
The user is not able to create or edit Hosts.

## Steps to Reproduce (for bugs)
1. Create a role and filter, like:
```
[role01]
users = "limited-user"
permissions = "module/director, director/audit, director/showconfig, director/hosts, module/monitoring, monitoring/command/schedule-check, monitoring/command/acknowledge-problem, monitoring/command/comment/add, monitoring/command/downtime/*"
director/filter/hostgroups = "group01"
```
2. Create the respective user, hostgroup and a test host.
3. Assign the test host to group01 
4. Change to the limited-user
5. Go to director->hosts and try to add a new host. You will get following error:
```
No such object available

#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(328): Icinga\Module\Director\Web\Controller\ObjectController->loadObject()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(62): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
#2 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Director\Web\Controller\ObjectController->init()
#3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#7 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#8 {main}
```
Regardless of that error the host will be created.

## Context
I try to set display permissions/restrictions to users

## Your Environment
* Icinga Web 2 version and modules (System - About):
```
MODULE         VERSION   STATE     DESCRIPTION
businessprocess 2.0.0-rc1 enabled   A Business Process viewer and modeler
director       1.4.0     enabled   Director - Config tool for Icinga 2
fileshipper    1.0.0     enabled   Fileshipper for Icinga Director
monitoring     2.4.1     enabled   Icinga monitoring module
```

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 14.04.5 LTS, Trusty Tahr
  Kernel: Linux
  Kernel version: 3.13.0-101-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.2
  Build host: 02a0e862c14c

```
* Operating System and version:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
* Enabled features (`icinga2 feature list`):
```
Disabled features: gelf graphite ido-pgsql influxdb livestatus logstash opentsdb perfdata redis syslog
Enabled features: api checker command compatlog debuglog ido-mysql mainlog notification statusdata

```
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: box18.int.netways.de
warning/ApplyRule: Apply rule 'satellite-host' (in /var/lib/icinga2/api/zones/global-templates/_etc/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'apt' (in /var/lib/icinga2/api/zones/global-templates/_etc/apt.conf: 1:0-1:18) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'ping6' (in /var/lib/icinga2/api/zones/global-templates/_etc/services.conf: 34:1-34:21) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'ssh' (in /var/lib/icinga2/api/zones/global-templates/_etc/services.conf: 47:1-47:19) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule '' (in /var/lib/icinga2/api/zones/global-templates/_etc/services.conf: 57:1-57:65) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule '' (in /var/lib/icinga2/api/zones/global-templates/_etc/services.conf: 65:1-65:53) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'icinga' (in /var/lib/icinga2/api/zones/global-templates/_etc/services.conf: 73:1-73:22) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 2 FileLoggers.
information/ConfigItem: Instantiated 3 Endpoints.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 6 Notifications.
information/ConfigItem: Instantiated 207 CheckCommands.
information/ConfigItem: Instantiated 6 Downtimes.
information/ConfigItem: Instantiated 3 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 5 HostGroups.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 14 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 6 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 StatusDataWriter.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

```
Regards

**Comment by dnsmichi** [comment]
This sounds like an issue with module specific permissions. Please create an issue over at the Director project.

**Comment by darmagan** [comment]
ref:
https://github.com/Icinga/icingaweb2-module-director/issues/1246
