### ISSUE TITLE
Receive LDAP error logging into icingaweb2 when using php71 and multiple domain controllers

### ISSUE THREAD

**Issue by bl4kd3th** [Icinga/icingaweb2#3066]
```
ldap_connect(): Could not create session handle: Bad parameter to an ldap routine

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'ldap_connect():...', '/usr/share/php/...', 1176, Array)
#1 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(1176): ldap_connect('dc01 dc02', '389')
#2 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(236): Icinga\Protocol\Ldap\LdapConnection->prepareNewConnection()
#3 /usr/share/php/Icinga/Protocol/Ldap/LdapCapabilities.php(273): Icinga\Protocol\Ldap\LdapConnection->getConnection()
#4 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(251): Icinga\Protocol\Ldap\LdapCapabilities::discoverCapabilities(Object(Icinga\Protocol\Ldap\LdapConnection))
#5 /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php(224): Icinga\Protocol\Ldap\LdapConnection->getCapabilities()
#6 /usr/share/php/Icinga/Repository/Repository.php(345): Icinga\Authentication\User\LdapUserBackend->initializeQueryColumns()
#7 /usr/share/php/Icinga/Repository/Repository.php(298): Icinga\Repository\Repository->getQueryColumns()
#8 /usr/share/php/Icinga/Repository/Repository.php(703): Icinga\Repository\Repository->getBaseTable()
#9 /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php(377): Icinga\Repository\Repository->select()
#10 /usr/share/php/Icinga/Authentication/AuthChain.php(114): Icinga\Authentication\User\LdapUserBackend->authenticate(Object(Icinga\User), 'asd')
#11 /usr/share/icingaweb2/application/forms/Authentication/LoginForm.php(91): Icinga\Authentication\AuthChain->authenticate(Object(Icinga\User), 'asd')
#12 /usr/share/php/Icinga/Web/Form.php(1158): Icinga\Forms\Authentication\LoginForm->onSuccess()
#13 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(50): Icinga\Web\Form->handleRequest()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('loginAction')
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#20 {main}
```

## Expected Behavior
When providing multiple DCs it should try one, and then the other.

## Current Behavior
Passing both DC hostnames into the ldap_connect function (see line #1 in error above).

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
0. need to have php71 installed. I used this resource https://webtatic.com/packages/php71/.
1. modify icingaweb2 resources (/etc/icingaweb2/resources.ini), in the hostname section of ldap resource, add a second hostname
2. attempt login to icingaweb2
3. receive error at the top

## Context
I wanted to upgrade to php71 to see how it affected performance. Upgrade went alright but immediately received that error when trying to login to web interface. Removing the second host entry on the ldap resource allowed me to login.

## Your Environment
Icinga Web 2: Version 2.4.2, Git commit 7cec28a31fdff0feb470ec001838bc1dec9c4b69
Icinga2: version: r2.7.1-1
OS: CentOS Linux release 7.4.1708 (Core)
Features: Enabled features: api checker ido-mysql influxdb mainlog notification
Config:
```
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: host.domain.local
warning/InfluxdbWriter: 'socket_timeout' option has no effect and will be removed in Icinga 2 v2.8
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 276 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 208 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 3 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 34 Hosts.
information/ConfigItem: Instantiated 19 Comments.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 143 Services.
information/ConfigItem: Instantiated 4 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

**Comment by nilmerg** [comment]
Hi,

please try using LDAP-URIs instead of just the hostnames. As per the PHP documentation for [ldap_connect()](http://php.net/manual/en/function.ldap-connect.php) states only multiple URIs are supported. (`ldap://dc01:389 ldap://dc02:389` in your case)

@lippserd 
We're already adding appropriate protocol schemes if SSL is selected as encryption. If not, users need to provide proper URIs themselves. We may do the same in this case, though? (At least clarifying this requirement in the tooltip..)

**Comment by bl4kd3th** [comment]
Thanks @nilmerg, your suggestion worked. When I used the example you provided, it validated successfully and allowed me to save the config. 

Tooltip still suggests to provide list of hostnames separated by space. Perhaps need to update the tooltip? Or maybe introduce handling to create the LDAP URI string using Host+Port values if multiple hostnames are provided?
