### ISSUE TITLE
Shared Navigation-chose issue?no name of navigation.

### ISSUE THREAD

**Issue by cryerenable** [Icinga/icingaweb2#3176]
Hello
Shared Navigation
1#Screen shoot: https://i.imgur.com/xJ23BqX.png
```
Required parameter 'name' missing

#0 /usr/share/icingaweb2/application/controllers/NavigationController.php(253): Icinga\Web\UrlParams->getRequired('name')
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\NavigationController->editAction()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('editAction')
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#7 {main}
```
2#Screenshoot: https://i.imgur.com/y6gUQ0n.png
Unshare ERROR
```
script 'navigation/unshare.phtml' not found in path (/usr/share/icingaweb2/application/views/scripts/)

#0 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(873): Zend_View_Abstract->_script('navigation/unsh...')
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render('navigation/unsh...')
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('navigation/unsh...', NULL)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('unshareAction')
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#11 {main}
```
3#Screenshoot: https://i.imgur.com/8B95jzz.png

I checked the file **menu.ini**: 
```
[123123123]
users = "123"
groups = "123"
type = "menu-item"
target = "_main"
url = "123123"
owner = "cryerenable"
```

**Icinga2-version**:r2.8.0-1
**Icingaweb2-version**:2.5.0

**Disabled features:**   compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb   perfdata statusdata syslog 
**Enabled features:** api checker command   ido-mysql mainlog notification 
```
icinga2 daemon -c

information/cli: Icinga application loader (version: r2.8.0-1) |  
-- | --
information/cli:   Loading configuration file(s). |  
information/ConfigItem:   Committing config item(s). |  
information/ApiListener:   My API identity: icinga.xyz |  
information/ConfigItem:   Instantiated 1 ApiListener. |  
information/ConfigItem:   Instantiated 3 Zones. |  
information/ConfigItem:   Instantiated 1 Endpoint. |  
information/ConfigItem:   Instantiated 1 ApiUser. |  
information/ConfigItem:   Instantiated 1 FileLogger. |  
information/ConfigItem:   Instantiated 1 NotificationComponent. |  
information/ConfigItem:   Instantiated 13 Notifications. |  
information/ConfigItem:   Instantiated 2 NotificationCommands. |  
information/ConfigItem:   Instantiated 209 CheckCommands. |  
information/ConfigItem:   Instantiated 1 Downtime. |  
information/ConfigItem:   Instantiated 3 HostGroups. |  
information/ConfigItem:   Instantiated 1 IcingaApplication. |  
information/ConfigItem:   Instantiated 1 Host. |  
information/ConfigItem:   Instantiated 1 UserGroup. |  
information/ConfigItem:   Instantiated 1 User. |  
information/ConfigItem:   Instantiated 3 TimePeriods. |  
information/ConfigItem:   Instantiated 12 Services. |  
information/ConfigItem:   Instantiated 3 ServiceGroups. |  
information/ConfigItem:   Instantiated 1 ScheduledDowntime. |  
information/ConfigItem:   Instantiated 1 ExternalCommandListener. |  
information/ConfigItem:   Instantiated 1 IdoMysqlConnection. |  
information/ConfigItem:   Instantiated 1 CheckerComponent. |  
information/ScriptGlobal:   Dumping variables to file '/var/cache/icinga2/icinga2.vars' |  
information/cli:   Finished validating the configuration file(s). |  

```

**Comment by cryerenable** [comment]
I fix this bug for me
delete in /etc/icingaweb2/preferences/user/menu.ini all lines of this Navigation item.
