### ISSUE TITLE
Strict config ini parser throws exceptions, hides file location

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#3252]
## Expected Behavior

An error message with indications on how to solve the issue.

## Current Behavior

ParseIniFile throws an exception which renders a stacktrace. Users believe it is a bug, still it is just a more strict ini file parsing.

```
syntax error, unexpected '=' in Unknown on line 2
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'syntax error, u...', '/usr/local/shar...', 263, Array)
#1 /usr/local/share/icingaweb2/library/Icinga/File/Ini/IniParser.php(263): parse_ini_string('[security]\nprot...', true)
#2 /usr/local/share/icingaweb2/library/Icinga/Application/Config.php(326): Icinga\File\Ini\IniParser::parseIniFile('/usr/local/icin...')
#3 /usr/local/share/icingaweb2/library/Icinga/Application/Config.php(421): Icinga\Application\Config::fromIni('/usr/local/icin...')
#4 /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php(424): Icinga\Application\Config::module('monitoring')
#5 /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php(768): Icinga\Module\Monitoring\Object\MonitoredObject->fetchCustomvars()
#6 /usr/local/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(61): Icinga\Module\Monitoring\Object\MonitoredObject->populate()
#7 /usr/local/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(66): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#8 /usr/local/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction()
#9 /usr/local/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#10 /usr/local/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/local/share/icingaweb2/library/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/local/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#13 /usr/local/share/icingaweb2/public/index.php(4): require_once('/usr/local/shar...')
#14 {main}
```

The location is hidden as the string is too long.

## Possible Solution

Catch the exception, and re-throw with more helpful details.

## Steps to Reproduce (for bugs)

1. Edit `/etc/icingaweb2/modules/monitoring/config.ini`
2. 

```
[security]
protected_customvars = abc = *pw*,*pass*,community
```

## Context

Affects likely many who upgrade to v2.5.0.

Discussed this with @lippserd 5 minutes ago, this originates from the change from the self-written parser to the PHP library version in v2.5.0.

## Your Environment

* Icinga Web 2 version and modules (System - About): v2.5.0 (and git master variants), PHP 7.x
* Version used (`icinga2 --version`): v2.8.0
* Operating System and version: macOS, also Linux flavours

**Comment by lippserd** [comment]
@nilmerg Please fix
