### ISSUE TITLE
Running setup again leads to fatal error

### ISSUE THREAD

**Issue by Hipska** [Icinga/icingaweb2#3316]
I have installed latest version of Icingaweb2 and finished setup procedure. But when loading the setup page again, I came across this error message:

```
PHP Fatal error:  Uncaught ErrorException: Undefined variable: messages in zend.view:///usr/share/icingaweb2/application/views/scripts/error/error.phtml:15
Stack trace:
#0 zend.view:///usr/share/icingaweb2/application/views/scripts/error/error.phtml(15): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined varia...', 'zend.view:///us...', 15, Array)
#1 /usr/share/php/Icinga/Web/View.php(270): include('zend.view:///us...')
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('error/error.pht...', NULL)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#6 /usr/share/icingawe in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332
```

## Steps to Reproduce (for bugs)
1. Install Icingaweb2
2. Finish `/icingaweb2/setup` from browser
3. Log in
4. Open `/icingaweb2/setup` again

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7.4

**Comment by Al2Klimov** [comment]
Hello @Hipska and thank you for reporting!

Does the above change solve your problem?

Best,
AK
