### ISSUE TITLE
Icingaweb2: icinga2 transport can't negotiate a encryption algorithm when Icinga2 api.conf limits ciphers

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [Icinga/icingaweb2#3471]
When Icinga2 API configuration limits the cipher_list, Icingaweb2 can no longer communicate with Icinga2 using the icinga2 transport.

## Expected Behavior
Icingaweb2 is able to communicate using the Icinga2 API as transport and/or the cipher list can be configured in the Icingaweb2 `transport.ini` for icinga2 transport.

## Current Behavior
When Icinga2 API configuration limits the cipher_list, e.g.:

```
object ApiListener "api" {

  // accept remote commands
  accept_commands = true

  tls_protocolmin = "TLSv1.2"
  cipher_list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
}
```

the Icingaweb2 can no longer communicate using the Icinga2 transport and fail with:

```
icinga2: Cannot communicate securely with peer: no common encryption algorithm(s).

#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php(163): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\AcknowledgeProblemCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1154): Icinga\Module\Monitoring\Forms\Command\Object\AcknowledgeProblemCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(122): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(79): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->handleCommandForm(Object(Icinga\Module\Monitoring\Forms\Command\Object\AcknowledgeProblemCommandForm))
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->acknowledgeProblemAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#10 {main}
```

According to the current Icingaweb2 documentation (https://www.icinga.com/docs/icingaweb2/latest/modules/monitoring/doc/05-Command-Transports/) there is no way to specify a cipher list for this transport.

## Steps to Reproduce (for bugs)
1. Limit cipherlist as described above
2. Restart `icinga2.service`
3. Restart `nginx.service` and `rh-php71-php-fpm.service` (just to be sure)
4. e.g. acknowledge a service problem in the Web UI

## Context
The primary reason was to disable DES-CBC3-SHA for Icinga2 on RHEL/CentOS 6 (only RHEL/CentOS 6, RHEL/CentOS 7 does no longer offer DES-CBC3-SHA).

## Your Environment
* Icinga Web 2 version: 
Icinga Web 2 Version 2.5.3 Git Commit ca7e886b820f0145999fdf7377f5c4132301eada Git Commit Datum 2018-04-27

* Version used (`icinga2 --version`): r2.8.2-1
* Operating System and version:
Icinga2 master: CentOS Linux release 7.5.1804 (Core) 
Icinga2 clients: CentOS release 6.9 (Final), CentOS Linux release 7.5.1804 (Core), Red Hat Enterprise Linux Workstation release 6.9 (Santiago), Red Hat Enterprise Linux Server release 6.9 (Santiago)

* Enabled features (`icinga2 feature list`):
Master: `api checker ido-pgsql mainlog notification`
Clients: `api checker mainlog syslog`

* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.8.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: __removed_because_of_nda__
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 445 Zones.
information/ConfigItem: Instantiated 445 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 3 ApiUsers.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 9398 Notifications.
information/ConfigItem: Instantiated 271 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 836 Hosts.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 61 Comments.
information/ConfigItem: Instantiated 8562 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

Icingaweb2 runs on `CentOS Linux release 7.5.1804 (Core)`.
Webserver is:

```
nginx version: nginx/1.14.0
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --user=nginx --group=nginx --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-file-aio --with-mail_ssl_module --with-ipv6 --with-stream --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --add-module=/home/build/nginx_http_auth_pam_module/ngx_http_auth_pam_module --with-ld-opt=-Wl,-E
```

using `rh-php71-php-fpm-7.1.8-1.el7` from the official CentOS software collection.

**Note:** I don't think it is a bug, merely a missing configuration option in `transport.ini`

**Comment by nilmerg** [comment]
Hi,

to disable a specific cipher please configure this appropriately in Icinga 2 instead:

`cipher_list = "ALL:!LOW:!WEAK:!MEDIUM:!EXP:!NULL:!DES-CBC3-SHA"`

This way you don't need to change anything on the Icinga Web 2 side.

Also, the ciphers you're mentioning are unlikely to be supported by curl for php anyway, which we're using to communicate with Icinga 2.
