### ISSUE TITLE
icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.

### ISSUE THREAD

**Issue by ketnerp** [Icinga/icingaweb2#3561]
Hello guys, as I m a newbie on GitHub I m sorry if I forgot to write anything important.
I m facing a problem where I cannot re-take test or make any remote operation via icinga2 webgui like Check now, Acknowledge, etc.. Everytime it writes the code written below...
As I read like 20-30 issues and articles about that, I tried many things. 
AS first, SELinux is DISABLED.
my httpd user as is apache is in all important groups i think:
`[root@icinga cmd]# id apache`
`uid=48(apache) gid=989(php-fpm) skupiny=989(php-fpm),992(icingacmd),991(icingaweb2)

If anything will be needed, just write it, please, I will share every needed info to get out of this situation. Thanks a lot and below is my issue:
`

## Expected Behavior
I m expecting that icingaweb2 will re-take test when I ask her for it.

## Current Behavior
When I look closer to some alarm and then use any of functions: Acknowledge, Check now, Comment, Notification, Downtime, Icinga2web responds:

> icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.

> 
> #0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(70): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceCheckCommand))
> #1 /usr/share/php/Icinga/Web/Form.php(1158): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
> #2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(275): Icinga\Web\Form->handleRequest()
> #3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(60): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->setupQuickActionForms()
> #4 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(66): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
> #5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction()
> #6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
> #7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
> #8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
> #9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
> #10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
> #11 {main}

## Possible Solution
I was thinking if there is not any problem with permissions.

## Steps to Reproduce (for bugs)

1.https://www.vultr.com/docs/how-to-install-icinga-2-and-icinga-web-2-on-centos-7

## Context
I cannot re-take test when I want to.

## Your Environment

* Icinga Web 2 version and modules (System - About):

> icingaweb2.noarch                2.6.1-1.el7.icinga 

* Version used (`icinga2 --version`):

> icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)
> 
> Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Application information:
>   Installation root: /usr
>   Sysconf directory: /etc
>   Run directory: /run
>   Local state directory: /var
>   Package data directory: /usr/share/icinga2
>   State path: /var/lib/icinga2/icinga2.state
>   Modified attributes path: /var/lib/icinga2/modified-attributes.conf
>   Objects path: /var/cache/icinga2/icinga2.debug
>   Vars path: /var/cache/icinga2/icinga2.vars
>   PID path: /run/icinga2/icinga2.pid
> 
> System information:
>   Platform: CentOS Linux
>   Platform version: 7 (Core)
>   Kernel: Linux
>   Kernel version: 3.10.0-862.11.6.el7.x86_64
>   Architecture: x86_64
> 
> Build information:
>   Compiler: GNU 4.8.5
>   Build host: unknown
> 
 Operating System and version:

> CentOS Linux release 7.5.1804 (Core)

Enabled features (`icinga2 feature list`):

> Disabled features: api compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
> Enabled features: checker command ido-mysql mainlog notification

Config validation (`icinga2 daemon -C`):

> [root@icinga icingaweb2]# icinga2 daemon -C
[2018-08-21 17:23:35 +0200] information/cli: Icinga application loader (version: r2.9.1-1)
[2018-08-21 17:23:35 +0200] information/cli: Loading configuration file(s).
[2018-08-21 17:23:35 +0200] information/ConfigItem: Committing config item(s).
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 11 Services.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 Host.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 Downtime.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 3 Zones.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 213 CheckCommands.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2018-08-21 17:23:35 +0200] information/ConfigItem: Instantiated 1 User.
[2018-08-21 17:23:35 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2018-08-21 17:23:35 +0200] information/cli: Finished validating the configuration file(s).

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Such questions are perfect for our community support channels: https://www.icinga.com/community/

Anyways, I'll try to point you in the right direction. First, make sure that the file exists. Next, try to write to the file as your web server user. If it's not working, fix the permissions.
Remember, if you change group memberships of your web server's user, make sure to restart the web server afterwards.

Best,
Eric
