### ISSUE TITLE
Updating a navigation item results in persistent Icingaweb2 crash

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icingaweb2#3565]
## Expected Behavior
An existing navigation item which have a parent item shall be reconfigured as shared item.

## Current Behavior
Removing parent and enabling as shared item in one step results in Icingaweb2 crash:
```
**Fatal error** : Uncaught ErrorException: Uncaught Icinga\Exception\ConfigurationError: Failed to fully parse navigation configuration. Ensure that all referenced parents are existing navigation items: Service Grids in /usr/share/php/Icinga/Web/Navigation/Navigation.php:547 Stack trace: #0 /usr/share/php/Icinga/Application/Web.php(277): Icinga\Web\Navigation\Navigation::fromConfig(Array) #1 /usr/share/php/Icinga/Web/Navigation/Navigation.php(437): Icinga\Application\Web-&gt;getSharedNavigation('menu-item') #2 /usr/share/php/Icinga/Web/Menu.php(21): Icinga\Web\Navigation\Navigation-&gt;load('menu-item') #3 zend.view:///usr/share/icingaweb2/application/layouts/scripts/parts/navigation.phtml(29): Icinga\Web\Menu-&gt;__construct() #4 /usr/share/php/Icinga/Web/View.php(259): include('zend.view:///us...') #5 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View-&gt;_run('/usr/share/icin...') #6 zend.view:///usr/share/icingaweb2/application/layouts/scripts/body.phtml(45): Zend_View_Abstract-&gt;render(NULL) #7 /usr/shar in **/usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php** on line **259**
```

## Possible Solution
Item's entry in /etc/icingaweb2/navigation/menu.ini keeps parent item (which is not allowed for shared items). Removing this parent setting fix this issue.

## Your Environment
* Icinga Web 2 version: 2.6.1-1.xenial

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I can confirm this bug. You may circumvent this behavior if you save the navigation item after you've removed the parent and before you share. This extra step shouldn't be necessary of course and we'll fix it.

Best,
Eric
