### ISSUE TITLE
Usergroups not loaded for externally authenticated users

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#3583]
In case of external authentication, usergroups may not be loaded correctly for users authenticated this way.

The log shows this if the issue occurs:

> 2018-10-02T10:22:34+00:00 - ERROR - Can't get group memberships for user 'foobar' from backend 'groupOfUniqueNames'. An exception was thrown: Icinga\Exception\ConfigurationError in /vagrant/library/Icinga/Authentication/User/UserBackend.php:74 with message: User backends not set up. Please contact your Icinga Web administrator

## Steps to Reproduce (for bugs)
1. Install/Enable the grafana or business process module (known examples)
2. Login/Logout using external authentication
3. Notice that you don't see any dashlets/menu entries
4. Take a look into the log where the mentioned message appears

## Your Environment
master/vagrant

**Comment by nilmerg** [comment]
The full stacktrace:

```
User backends not set up. Please contact your Icinga Web administrator in /vagrant/library/Icinga/Authentication/User/UserBackend.php:74
Stack trace:
#0 /vagrant/library/Icinga/Authentication/User/UserBackend.php(156): Icinga\Authentication\User\UserBackend::assertBackendsExist()
#1 /vagrant/library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php(799): Icinga\Authentication\User\UserBackend::create('local-ldap')
#2 /vagrant/library/Icinga/Authentication/UserGroup/UserGroupBackend.php(160): Icinga\Authentication\UserGroup\LdapUserGroupBackend->setConfig(Object(Icinga\Data\ConfigObject))
#3 /vagrant/library/Icinga/Authentication/Auth.php(144): Icinga\Authentication\UserGroup\UserGroupBackend::create('posixGroup', Object(Icinga\Data\ConfigObject))
#4 /vagrant/library/Icinga/Authentication/Auth.php(267): Icinga\Authentication\Auth->setAuthenticated(Object(Icinga\User))
#5 /vagrant/library/Icinga/Authentication/Auth.php(93): Icinga\Authentication\Auth->authExternal()
#6 /vagrant/library/Icinga/Authentication/Auth.php(337): Icinga\Authentication\Auth->isAuthenticated()
#7 /usr/share/icingaweb2/modules/<a-module>/configuration.php(6): Icinga\Authentication\Auth->hasPermission('foo')
#8 /vagrant/library/Icinga/Application/Modules/Module.php(1227): include('/usr/share/icin...')
#9 /vagrant/library/Icinga/Application/Modules/Module.php(1245): Icinga\Application\Modules\Module->includeScript('/usr/share/icin...')
#10 /vagrant/library/Icinga/Application/Modules/Module.php(561): Icinga\Application\Modules\Module->launchConfigScript()
#11 /vagrant/library/Icinga/Web/JavaScript.php(92): Icinga\Application\Modules\Module->hasJs()
#12 /vagrant/library/Icinga/Web/JavaScript.php(55): Icinga\Web\JavaScript::send(true)
#13 /vagrant/library/Icinga/Application/webrouter.php(70): Icinga\Web\JavaScript::sendMinified()
#14 /vagrant/public/index.php(4): require_once('/vagrant/librar...')
#15 {main}
```

**Comment by nilmerg** [comment]
Another one:

```
User backends not set up. Please contact your Icinga Web administrator in /vagrant/library/Icinga/Authentication/User/UserBackend.php:74
Stack trace:
#0 /vagrant/library/Icinga/Authentication/User/UserBackend.php(156): Icinga\Authentication\User\UserBackend::assertBackendsExist()
#1 /vagrant/library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php(799): Icinga\Authentication\User\UserBackend::create('local-ldap')
#2 /vagrant/library/Icinga/Authentication/UserGroup/UserGroupBackend.php(160): Icinga\Authentication\UserGroup\LdapUserGroupBackend->setConfig(Object(Icinga\Data\ConfigObject))
#3 /vagrant/library/Icinga/Authentication/Auth.php(144): Icinga\Authentication\UserGroup\UserGroupBackend::create('posixGroup', Object(Icinga\Data\ConfigObject))
#4 /vagrant/library/Icinga/Authentication/Auth.php(267): Icinga\Authentication\Auth->setAuthenticated(Object(Icinga\User))
#5 /vagrant/library/Icinga/Authentication/Auth.php(93): Icinga\Authentication\Auth->authExternal()
#6 /vagrant/library/Icinga/Authentication/Auth.php(337): Icinga\Authentication\Auth->isAuthenticated()
#7 /usr/share/icingaweb2/modules/<a-module>/configuration.php(6): Icinga\Authentication\Auth->hasPermission('foo')
#8 /vagrant/library/Icinga/Application/Modules/Module.php(1227): include('/usr/share/icin...')
#9 /vagrant/library/Icinga/Application/Modules/Module.php(1245): Icinga\Application\Modules\Module->includeScript('/usr/share/icin...')
#10 /vagrant/library/Icinga/Application/Modules/Module.php(508): Icinga\Application\Modules\Module->launchConfigScript()
#11 /vagrant/library/Icinga/Web/StyleSheet.php(102): Icinga\Application\Modules\Module->hasCss()
#12 /vagrant/library/Icinga/Web/StyleSheet.php(87): Icinga\Web\StyleSheet->collect()
#13 /vagrant/library/Icinga/Web/StyleSheet.php(177): Icinga\Web\StyleSheet->__construct()
#14 /vagrant/library/Icinga/Application/webrouter.php(62): Icinga\Web\StyleSheet::send(true)
#15 /vagrant/public/index.php(4): require_once('/vagrant/librar...')
#16 {main}
```

**Comment by nilmerg** [comment]
This has been previously reported: #3470
