### ISSUE TITLE
Clicking on monitored host fails with php7.2

### ISSUE THREAD

**Issue by soostdijck** [Icinga/icingaweb2#3641]
I've just set up a fresh server with nginx and php-fpm (7.2) from the ius repo. Almost everything seems fine but when I click on a monitored host under 'overview > hosts > the only host I've got' I get an error, as per below.

## Expected Behavior
Get host details.

## Current Behavior
Error:
```
Dec  4 14:33:57 icingaweb2[112253]: 
ErrorException in /export/icingaweb2-2.6.2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php:513 
with message: 
Uncaught Error: Call to undefined function Icinga\Module\Monitoring\Object\json_decode() in /export/icingaweb2-2.6.2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php:513    

Stack trace:    
#0 /export/icingaweb2-2.6.2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php(439): Icinga\Module\Monitoring\Object\MonitoredObject->fetchHostVariables()    
#1 /export/icingaweb2-2.6.2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php(769): Icinga\Module\Monitoring\Object\MonitoredObject->fetchCustomvars()    
#2 /export/icingaweb2-2.6.2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(62): Icinga\Module\Monitoring\Object\MonitoredObject->populate()    
#3 /export/icingaweb2-2.6.2/modules/monitoring/application/controllers/HostController.php(61): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()   
 #4 /export/icingaweb2-2.6.2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostController->showAction    
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()   
 #1 {main}
```

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`): 2.6.2
* Operating System and version: CentOS 7.6.1810
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): 'all OK'
* php versions:
```
php72u-cli-7.2.12-1.ius.centos7.x86_64
php72u-opcache-7.2.12-1.ius.centos7.x86_64
php72u-json-7.2.12-1.ius.centos7.x86_64
php72u-intl-7.2.12-1.ius.centos7.x86_64
php72u-pecl-imagick-3.4.3-1.ius.centos7.x86_64
php72u-ldap-7.2.12-1.ius.centos7.x86_64
php72u-pdo-7.2.12-1.ius.centos7.x86_64
php72u-fpm-7.2.12-1.ius.centos7.x86_64
php72u-xml-7.2.12-1.ius.centos7.x86_64
php72u-gd-7.2.12-1.ius.centos7.x86_64
php72u-common-7.2.12-1.ius.centos7.x86_64
php72u-mysqlnd-7.2.12-1.ius.centos7.x86_64
```

**Comment by lippserd** [comment]
Hi,

Why aren't you using SCL and our packages? Did you install `php72u-json` after `php72u-fpm`? If so, did you already restart php-fpm? Does `json_decode/encode` work on the CLI?

Best,
Eric

**Comment by soostdijck** [comment]
Because I'm a stubborn bastard :) Your hunch was absolutely correct though, I installed `php72u-json` later on and php-fpm needed a restart. Sorry for the trouble!
