### ISSUE TITLE
Uncaught ErrorException: Uncaught Error: Class 'Zend_Form' not found in /usr/share/webapps/icingaweb2/library/Icinga/Web/Form.php:27

### ISSUE THREAD

**Issue by phreeek** [Icinga/icingaweb2#3692]
Hi,

I have problems with icingaweb2 on arch linux after an update to the latest version of _php-fpm_. I fixed a few stacktraces regarding "continue" statements. But I got stuck with this one:

### Stacktrace:
```
#0 /usr/share/webapps/icingaweb2/library/Icinga/Application/ClassLoader.php(303): require()
#1 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\Web\\Form')
#2 /usr/share/webapps/icingaweb2/application/forms/AutoRefreshForm.php(16): spl_autoload_call('Icinga\\Web\\Form')
#3 /usr/share/webapps/icingaweb2/library/Icinga/Application/ClassLoader.php(303): require('/usr/share/weba...')
#4 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\Forms\\Au...')
#5 /usr/share/webapps/icingaweb2/library/Icinga/Web/Controller/ActionController.php(453): spl_autoload_call('Icinga\\Forms\\Au...')
#6 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Action.php(493): Icinga\Web\Controller\ActionController->preDispatch()
#7 /usr/share/webapps/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controlle...PHP message: PHP Fatal error:  Uncaught ErrorException: Uncaught Error: Class 'Zend_Form' not found in /usr/share/webapps/icingaweb2/library/Icinga/Web/Form.php:27
```

## Expected Behavior
The login web-ui loads.

## Current Behavior
I see the stacktrace from above.

## Possible Solution
I guess that icingaweb2 is not yet compatible with PHP 7.3.2 and the Zend Framework 3.3.2 at the moment. The naming convention with the "_" is not longer supported. Just a blind shot.

## Steps to Reproduce (for bugs)
1. Visit the link: https://<domain>/authentication/login

## Context
I'd like to use icingaweb2 on a rolling release. ^^

## Your Environment
* PHP-Version
> PHP 7.3.2 (cli) (built: Feb  5 2019 19:18:41) ( NTS )

* Zend Framework Version
> Zend engine version: 3.3.2

* Nginx
> nginx version: nginx/1.14.2
```
user http http;
worker_processes  4;
worker_priority 15;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    limit_req_zone  $binary_remote_addr  zone=gulag:1m   rate=250r/m;

    server {
        listen       80;
        server_name  icinga.chaos.lan;
	
	access_log /var/log/icingaweb2/access_80.log;
	error_log /var/log/icingaweb2/error_80.log info;

	rewrite ^ https://$server_name$request_uri? permanent;
    }

    server {
	listen 443 ssl;
	server_name icinga.chaos.lan;

	access_log /var/log/icingaweb2/access_443.log;
	error_log /var/log/icingaweb2/error_443.log info;

        root  /usr/share/webapps/icingaweb2/public;
        index  index.php;

	gzip off;

	add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
	add_header X-Content-Type-Options nosniff;
	add_header X-Frame-Options "SAMEORIGIN";
	add_header X-XSS-Protection "1; mode=block";
	add_header X-Robots-Tag none;
	add_header X-Download-Options noopen;
	add_header X-Permitted-Cross-Domain-Policies none;

	limit_req   zone=gulag burst=200 nodelay;


	ssl on;
	ssl_certificate /etc/nginx/ssl/icinga.chaos.lan/chained_cert.pem;
	ssl_certificate_key /etc/nginx/ssl/icinga.chaos.lan/icinga-1key.pem;
	ssl_trusted_certificate /etc/ssl/chaos_pki/certs/ca.cert.pem;
	ssl_session_timeout  5m;
	ssl_session_cache shared:SSL:30m;
	keepalive_timeout    70;
	ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
	ssl_prefer_server_ciphers   on;
	ssl_dhparam /etc/nginx/ssl/icinga.chaos.lan/dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;

	location = /favicon.ico {
	    log_not_found off;
	    access_log off;
	    expires max;
	}

	location = /robots.txt {
	    allow all;
	    log_not_found off;
	    access_log off;
	}

	location ~ /\. {
	    deny all;
	    access_log off;
	    log_not_found off;
	}

	location ~ \..*/.*\.php$ {
	    return 403;
	}
	 
	if (!-d $request_filename) {
	    rewrite ^/(.+)/$ /$1 permanent;
	}

	location / {
	    try_files $1 $uri $uri/ /index.php$is_args$args;
	}

	location ~ ^/index\.php(.*)$ {
	    fastcgi_index index.php;
	    include /etc/nginx/fastcgi_params;
	    try_files $uri =404;
	    fastcgi_split_path_info ^(.+\.php)(/.+)$;
	    fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
	    fastcgi_param SCRIPT_FILENAME /usr/share/webapps/icingaweb2/public/index.php;
	    fastcgi_param ICINGAWEB_CONFIGDIR /etc/icingaweb2;
	    fastcgi_param REMOTE_USER $remote_user;
	}
    }
}
```

* Icinga Web 2 version and modules (System - About):
> aur/icingaweb2 2.6.2-1 [installed] (18) (0,09)

* Version used (`icinga2 --version`):
> aur/icinga2 2.10.2-1 [installed] (30) (0,09)

```
[2019-02-20 13:55:28 +0100] warning/Application: Failed adjust resource limit for number of processes (RLIMIT_NPROC) with error "Operation not permitted"
[2019-02-20 13:55:28 +0100] warning/Application: Failed adjust resource limit for number of processes (RLIMIT_NPROC) with error "Operation not permitted"
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Arch Linux ARM
  Platform version: Unknown
  Kernel: Linux
  Kernel version: 4.19.23-1-ARCH
  Architecture: armv7l

Build information:
  Compiler: GNU 8.2.1
  Build host: icinga

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Operating System and version:
```
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
```

* Enabled features (`icinga2 feature list`):
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite ido-pgsql livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql influxdb mainlog notification
```

* Config validation (`icinga2 daemon -C`):
```
[2019-02-20 13:58:21 +0100] information/cli: Icinga application loader (version: r2.10.2-1)
[2019-02-20 13:58:21 +0100] information/cli: Loading configuration file(s).
[2019-02-20 13:58:21 +0100] information/ConfigItem: Committing config item(s).
[2019-02-20 13:58:22 +0100] information/ApiListener: My API identity: icinga.chaos.lan
[2019-02-20 13:58:22 +0100] warning/ApplyRule: Apply rule 'Check LOAD (SNMP)' (in /var/lib/icinga2/api/packages/director/8ed4193c-1b75-4aea-88a8-146cd07a35ac/zones.d/director-global/service_apply.conf: 64:1-64:33) for type 'Service' does not match anywhere!
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 User.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 3 Zones.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 3 ServiceGroups.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 40 Services.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 2 HostGroups.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 9 Hosts.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 Endpoint.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 215 CheckCommands.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 ApiUser.
[2019-02-20 13:58:22 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2019-02-20 13:58:22 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-02-20 13:58:22 +0100] information/cli: Finished validating the configuration file(s).
```
If you need anything else, please let me know. :-)

cheers
phreeek

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Could you please test  icingaweb2-git and report back whether using our snapshot packages fixes your issue?

Best,
Eric

**Comment by nilmerg** [comment]
Hi,

I can't reproduce this with a simple test on v7.3.2:

```php
<?php

namespace My\Test {

    class Foo_Bar {
        public $foo = 'foo';
        public $bar = 'bar';
    }

}

namespace My\Other\Test {
    
    use My\Test\Foo_Bar;

    $fooBar = new Foo_Bar();
    echo $fooBar->foo;
    echo $fooBar->bar;

}
```

Please make sure that you've installed Icinga Web 2 properly. Note that we ship our own version of the Zend framwork (v1). If that's missing you'll get exactly such an error as you've shown above.

If that's not your issue and you're able to show us a minimal example (as I did above) of what's the cause please re-open.

**Comment by marxin** [comment]
I can confirm it works fine with `2.6.3` version! Thanks for the fix.
