### ISSUE TITLE
Graphs are Not Populating in Icinga2web

### ISSUE THREAD

**Issue by gintisaurabh** [Icinga/icingaweb2#3693]
Uncaught Error: Class 'Icinga\Module\Grafana\Helpers\Timeranges' not found in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php:503
<!-- Formatting tips:

GitHub supports Markdown: https://guides.github.com/features/mastering-markdown/
Multi-line code blocks either with three back ticks, or four space indent.

```
Stacktrace ...
Uncaught Error: Class 'Icinga\Module\Grafana\Helpers\Timeranges' not found in /usr/share/icingaweb2/modules/grafana/library/Grafana/ProvidedHook/Grapher.php:503
Stack trace:
#0 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/grapher.phtml(3): Icinga\Module\Grafana\ProvidedHook\Grapher->getPreviewHtml(Object(Icinga\Module\Monitoring\Object\Service))
#1 /usr/share/php/Icinga/Web/View.php(259): include('zend.view:///us...')
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#3 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/object/detail-content.phtml(3): Zend_View_Abstract->render(NULL)
#4 /usr/share/php/Icinga/Web/View.php(259): include('zend.view:///us...')
#5 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#6 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/service/show.p

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

**Comment by Mikesch-mp** [comment]
Please open a issue over at the [Grafana-module repository](https://github.com/Mikesch-mp/icingaweb2-module-grafana) and close this one here.

**Comment by gintisaurabh** [comment]
Done and closed, Hope will get help there.
