### ISSUE TITLE
Cannot update icingaweb2 to release 2.6.2-2

### ISSUE THREAD

**Issue by redbob365** [Icinga/icingaweb2#3715]
I followed instructions at issue #2893 to upgrade `icingaweb2`. However, this release is able just for Ubuntu 19.04 (cosmic) not yet released.

So, I [spinned icingaweb2 package](https://help.ubuntu.com/community/PinningHowto) and it uninstalled icingaweb2 and reinstalled icingacli, generating broken dependency.

I had to download all packages and install it one-by-one, as follows:
```
fonts-dejavu-extra_2.37-1_all.deb
php-icinga_2.6.2-2_all.deb
icingaweb2-common_2.6.2-2_all.deb
icingaweb2_2.6.2-2_all.deb
icingacli_2.6.1-1_all.deb
```
Now, when I try to open Web Interface (server/icingaweb2/authentication), it's giving me this error at browser:

`Fatal error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /usr/share/php/Icinga/Data/Db/DbConnection.php:196 Stack trace: #0 /usr/share/php/Icinga/Data/Db/DbConnection.php(76): Icinga\Data\Db\DbConnection->connect() #1 /usr/share/php/Icinga/Data/ResourceFactory.php(103): Icinga\Data\Db\DbConnection->__construct(Object(Icinga\Data\ConfigObject)) #2 /usr/share/php/Icinga/Data/ResourceFactory.php(136): Icinga\Data\ResourceFactory::createResource(Object(Icinga\Data\ConfigObject)) #3 /usr/share/php/Icinga/Authentication/User/UserBackend.php(210): Icinga\Data\ResourceFactory::create('icingaweb_db') #4 /usr/share/php/Icinga/Authentication/AuthChain.php(241): Icinga\Authentication\User\UserBackend::create('icingaweb2', Object(Icinga\Data\ConfigObject)) #5 /usr/share/php/Icinga/Authentication/Auth.php(272): Icinga\Authentication\AuthChain->valid() #6 /usr/share/php/Icinga/Authentication/Auth.php(93): Icinga\Authentication\Auth->authExternal() #7 /usr/share/php/Icinga/Authentication/Auth.php(348): Icinga\Au in /usr/share/php/Icinga/Data/Db/DbConnection.php on line 196`

Any ideas to solve this?

## Your Environment
* Icinga Web 2 version and modules: 2.6.2-2
* Version used (`icinga2 --version`): r2.10.3-1
* Operating System and version: Ubuntu 16.04.5
* Enabled features (`icinga2 feature list`): api checker command compatlog graphite ido-mysql influxdb livestatus mainlog notification perfdata statusdata
* Config validation (`icinga2 daemon -C`):
```
[2019-03-08 17:24:21 -0400] information/cli: Icinga application loader (version: r2.10.3-1)
[2019-03-08 17:24:21 -0400] information/cli: Loading configuration file(s).
[2019-03-08 17:24:21 -0400] information/ConfigItem: Committing config item(s).
[2019-03-08 17:24:22 -0400] information/ApiListener: My API identity: srvici-mt.mt.trf1.gov.br
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 96 Services.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 LivestatusListener.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 177 Hosts.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 FileLogger.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 2 NotificationCommands.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 13 HostGroups.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 ApiListener.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 3 Zones.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 StatusDataWriter.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 Endpoint.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 4 ApiUsers.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 CompatLogger.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 2 Users.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 222 CheckCommands.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 UserGroup.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 1 ServiceGroup.
[2019-03-08 17:24:22 -0400] information/ConfigItem: Instantiated 3 TimePeriods.
[2019-03-08 17:24:22 -0400] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-03-08 17:24:22 -0400] information/cli: Finished validating the configuration file(s).

```

**Comment by redbob365** [comment]
I already solved this issue, following these paths:

- Reinstalled `php7.0-mysql`;
- Reinstalled libapache2-mod-php7.0`;

After that, everything is running and icingaweb2 is now updated to 2.6.2
