### ISSUE TITLE
CurlException in RestRequest.php - API Timeout but curl from shell works fine

### ISSUE THREAD

**Issue by Duffkess** [Icinga/icingaweb2#3725]
I want to reschedule service checks, acknowledge problems and apply downtimes using the icingaweb2 interface.

when I do one of these things I get this error:

`icinga2: Operation timed out after 30000 milliseconds with 0 out of 0 bytes received.`

When looking in the icingaweb2.log I see:

```2019-03-21T15:39:16+01:00 - DEBUG - Sending Icinga command "actions/reschedule-check" to the API "node-a.domain.tld:5665"
2019-03-21T15:39:16+01:00 - DEBUG - Executing curl -s -X POST -H 'Accept: application/json' -k -u 'username':'password' -d '{"next_check":1553179156,"force":true,"host":"myhost"}' 'https://node-a.domain.tld:5665/v1/actions/reschedule-check'
2019-03-21T15:39:46+01:00 - ERROR - Icinga\Module\Monitoring\Exception\CurlException in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Rest/RestRequest.php:291 with message: Operation timed out after 30000 milliseconds with 0 out of 0 bytes received
2019-03-21T15:39:46+01:00 - ERROR - Icinga\Module\Monitoring\Exception\CommandTransportException in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Command/Transport/CommandTransport.php:137 with message: icinga2: Operation timed out after 30000 milliseconds with 0 out of 0 bytes received.
#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(70): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleHostCheckCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1158): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(275): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(60): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->setupQuickActionForms()
#4 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostController.php(61): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostController->showAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```

I also see the same stacktrace when using service php-fpm status -l

When using the provided curl command from the shell (even when run under apache user) it works just fine.

My commandtransports.ini look like this:
```[icinga2]
transport = "api"
host = "node-a.domain.tld"
port = "5665"
username = "username"
password = "password"
```

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version
    2.6.2
Git Commit
    63cb9d728338225833884fda2c312a5a9f431fd6

* Version used (`icinga2 --version`):
r2.10.4-1

* Operating System and version:
CentOS 7

**Comment by dnsmichi** [comment]
That's a problem with Icinga 2 and its API. Currently there's no workaround, you'll need to wait up until icinga/icinga2#7041 is implemented and released.

**Comment by dnsmichi** [comment]
You can test the snapshot packages of icinga2, the network stack related fixes for the API are in there.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Since this is a know Icinga 2 issue I'll close this one.

Best,
Eric
