### ISSUE TITLE
API Query exception

### ISSUE THREAD

**Issue by gjongenelen** [Icinga/icingaweb2#3800]
## Describe the bug
Exception is being thrown when querying director API with simple vars

<details><summary>Exception</summary>
<p>

```
{ "objects": [ {
    "error": "#0 \/usr\/share\/icingaweb2\/library\/vendor\/Zend\/Db\/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)\n#1 \/usr\/share\/icingaweb2\/library\/vendor\/Zend\/Db\/Adapter\/Abstract.php(470): Zend_Db_Statement->execute(Array)\n#2 \/usr\/share\/icingaweb2\/library\/vendor\/Zend\/Db\/Adapter\/Pdo\/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT o.* FROM...', Array)\n#3 \/usr\/share\/icingaweb2\/modules\/director\/library\/Director\/RestApi\/IcingaObjectsHandler.php(83): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))\n#4 \/usr\/share\/icingaweb2\/modules\/director\/library\/Director\/RestApi\/IcingaObjectsHandler.php(22): Icinga\\Module\\Director\\RestApi\\IcingaObjectsHandler->streamJsonResult()\n#5 \/usr\/share\/icingaweb2\/modules\/director\/library\/Director\/RestApi\/RequestHandler.php(32): Icinga\\Module\\Director\\RestApi\\IcingaObjectsHandler->processApiRequest()\n#6 \/usr\/share\/icingaweb2\/modules\/director\/library\/Director\/Web\/Controller\/ObjectsController.php(91): Icinga\\Module\\Director\\RestApi\\RequestHandler->dispatch()\n#7 \/usr\/share\/icingaweb2\/library\/vendor\/Zend\/Controller\/Action.php(507): Icinga\\Module\\Director\\Web\\Controller\\ObjectsController->indexAction()\n#8 \/usr\/share\/php\/Icinga\/Web\/Controller\/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')\n#9 \/usr\/share\/icingaweb2\/library\/vendor\/Zend\/Controller\/Front.php(937): Icinga\\Web\\Controller\\Dispatcher->dispatch(Object(Icinga\\Web\\Request), Object(Icinga\\Web\\Response))\n#10 \/usr\/share\/php\/Icinga\/Application\/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\\Web\\Request), Object(Icinga\\Web\\Response))\n#11 \/usr\/share\/php\/Icinga\/Application\/webrouter.php(104): Icinga\\Application\\Web->dispatch()\n#12 \/usr\/share\/icingaweb2\/public\/index.php(4): require_once('\/usr\/share\/php\/...')\n#13 {main}"
}
```
</p>
</details>

## To Reproduce
1. Create some services in the director
2. Query the director API for the service, supplying the host (ex. `/director/services?host=10.0.0.2`)

## Expected behavior
Same as `/director/services` but filtered 

## Environment
Master-master setup, MariaDB 10.3.15 backend

* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version used (`icinga2 --version`): r2.10.4-1
* PHP version used (`php --version`): Tested on 7.3.4 & 7.0
* Server operating system and version: Tested on Debian Buster & Stretch

## Additional context
Might be related to an old issue: #2508 but the solutions mentioned didn't solve the problem.

**Comment by dnsmichi** [comment]
This should be moved to the Director project, right?
