### ISSUE TITLE
After Update to 2.7.2 - Servicegroups for roles with filtered objects not available

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2#3983]
Hi all,
just updated to 2.7.2. After this, all of our teams are not able to see servicegroups anymore.
For me, as admin without filtered objects, everything still works.
Also any other filters (hosts, services, hostgroups) are still working for the teams. 
Example role:
```
[Team A]
groups = "Team A"
permissions = "module/grafana,grafana/showall,module/monitoring,monitoring/command/schedule-check,monitoring/command/acknowledge-problem,monitoring/command/remove-acknowledgement,monitoring/command/comment/add,monitoring/command/downtime/*,monitoring/command/send-custom-notification"
monitoring/filter/objects = "_host_team=*\"TeamA\"*|_service_team=*\"TeamA\"*"
```
The Error displayed in Icingaweb2 is:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'h.host_object_id' in 'on clause', query was: SELECT servicesgroupsummary.servicegroup_alias, servicesgroupsummary.servicegroup_name, SUM(CASE WHEN service_state = 2 AND service_handled = 1 THEN 1 ELSE 0 END) AS services_critical_handled, SUM(CASE WHEN service_state = 2 AND service_handled = 0 THEN 1 ELSE 0 END) AS services_critical_unhandled, SUM(CASE WHEN service_state = 0 THEN 1 ELSE 0 END) AS services_ok, SUM(CASE WHEN service_state = 99 THEN 1 ELSE 0 END) AS services_pending, SUM(1) AS services_total, SUM(CASE WHEN service_state = 3 AND service_handled = 1 THEN 1 ELSE 0 END) AS services_unknown_handled, SUM(CASE WHEN service_state = 3 AND service_handled = 0 THEN 1 ELSE 0 END) AS services_unknown_unhandled, SUM(CASE WHEN service_state = 1 AND service_handled = 1 THEN 1 ELSE 0 END) AS services_warning_handled, SUM(CASE WHEN service_state = 1 AND service_handled = 0 THEN 1 ELSE 0 END) AS services_warning_unhandled FROM (SELECT sg.alias COLLATE latin1_general_ci AS servicegroup_alias, sgo.name1 AS servicegroup_name, CASE WHEN (ss.problem_has_been_acknowledged + ss.scheduled_downtime_depth + COALESCE(hs.current_state, 0)) > 0 THEN 1 ELSE 0 END AS service_handled, CASE WHEN ss.current_state = 0 THEN CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 16 ELSE 0 END + CASE WHEN ss.problem_has_been_acknowledged = 1 THEN 2 ELSE CASE WHEN ss.scheduled_downtime_depth > 0 THEN 1 ELSE 4 END END ELSE CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 16 WHEN ss.current_state = 1 THEN 32 WHEN ss.current_state = 2 THEN 128 WHEN ss.current_state = 3 THEN 64 ELSE 256 END + CASE WHEN hs.current_state > 0 THEN 1024 ELSE CASE WHEN ss.problem_has_been_acknowledged = 1 THEN 512 ELSE CASE WHEN ss.scheduled_downtime_depth > 0 THEN 256 ELSE 2048 END END END END AS service_severity, CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 99 ELSE ss.current_state END AS service_state FROM icinga_objects AS sgo
INNER JOIN icinga_servicegroups AS sg ON sg.servicegroup_object_id = sgo.object_id AND sgo.objecttype_id = 4 AND sgo.is_active = 1
INNER JOIN icinga_servicegroup_members AS sgm ON sgm.servicegroup_id = sg.servicegroup_id
INNER JOIN icinga_objects AS so ON so.object_id = sgm.service_object_id AND so.objecttype_id = 2 AND so.is_active = 1
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_team ON s.host_object_id = hcv_team.object_id AND hcv_team.varname = 'team' COLLATE latin1_general_ci
LEFT JOIN icinga_customvariablestatus AS scv_team ON s.service_object_id = scv_team.object_id AND scv_team.varname = 'team' COLLATE latin1_general_ci WHERE ( ( (hcv_team.varvalue LIKE '%\"AppDev\"%' OR scv_team.varvalue LIKE '%\"AppDev\"%') OR (hcv_team.varvalue LIKE '%\"TeamA\"%' OR scv_team.varvalue LIKE '%\"TeamA\"%') ) ) GROUP BY sgo.object_id,
sg.servicegroup_id,
ss.servicestatus_id,
hs.hoststatus_id UNION ALL SELECT sg.alias COLLATE latin1_general_ci AS servicegroup_alias, sgo.name1 AS servicegroup_name, NULL AS service_handled, 0 AS service_severity, NULL AS service_state FROM icinga_objects AS sgo
INNER JOIN icinga_servicegroups AS sg ON sg.servicegroup_object_id = sgo.object_id AND sgo.objecttype_id = 4 AND sgo.is_active = 1
LEFT JOIN icinga_servicegroup_members AS esgm ON esgm.servicegroup_id = sg.servicegroup_id
INNER JOIN icinga_servicegroup_members AS sgm ON sgm.servicegroup_id = sg.servicegroup_id
INNER JOIN icinga_objects AS so ON so.object_id = sgm.service_object_id AND so.objecttype_id = 2 AND so.is_active = 1
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_team ON h.host_object_id = hcv_team.object_id AND hcv_team.varname = 'team' COLLATE latin1_general_ci
LEFT JOIN icinga_customvariablestatus AS scv_team ON s.service_object_id = scv_team.object_id AND scv_team.varname = 'team' COLLATE latin1_general_ci WHERE ( ( (hcv_team.varvalue LIKE '%\"AppDev\"%' OR scv_team.varvalue LIKE '%\"AppDev\"%') OR (hcv_team.varvalue LIKE '%\"TeamA\"%' OR scv_team.varvalue LIKE '%\"TeamA\"%') ) ) GROUP BY sgo.object_id,
sg.servicegroup_id,
sgo.object_id,
sg.servicegroup_id HAVING (COUNT(esgm.servicegroup_member_id) = 0)) AS servicesgroupsummary GROUP BY servicegroup_name,
servicegroup_alias ORDER BY servicegroup_alias ASC LIMIT 25

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Select.php(705): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 /usr/share/php/Icinga/Data/Db/DbConnection.php(100): Zend_Db_Select->query()
#5 /usr/share/php/Icinga/Data/SimpleQuery.php(171): Icinga\Data\Db\DbConnection->query(Object(Icinga\Module\Monitoring\Backend\Ido\Query\ServicegroupsummaryQuery))
#6 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/list/servicegroups.phtml(33): Icinga\Data\SimpleQuery->rewind()
#7 /usr/share/php/Icinga/Web/View.php(262): include(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#18 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#19 {main}

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'h.host_object_id' in 'on clause'

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php(219): PDOStatement->execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#4 /usr/share/icingaweb2/library/vendor/Zend/Db/Select.php(705): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /usr/share/php/Icinga/Data/Db/DbConnection.php(100): Zend_Db_Select->query()
#6 /usr/share/php/Icinga/Data/SimpleQuery.php(171): Icinga\Data\Db\DbConnection->query(Object(Icinga\Module\Monitoring\Backend\Ido\Query\ServicegroupsummaryQuery))
#7 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/list/servicegroups.phtml(33): Icinga\Data\SimpleQuery->rewind()
#8 /usr/share/php/Icinga/Web/View.php(262): include(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#20 {main}
```

## To Reproduce

1. Update to 2.7.2
2. Check the servicegroups for any role with filtered objects

## Expected behavior
Show the servicegroups

## Your Environment
* Icinga Web 2 version and modules (System - About):
grafana | 1.3.4
monitoring | 2.7.2
* Web browser used:
Chrome, Firefox
* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.0-1)
* PHP version used (`php --version`):
PHP 7.0.33-0ubuntu0.16.04.6 (cli) ( NTS )
* Server operating system and version:
System information:
  Platform: Ubuntu
  Platform version: 16.04.6 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-164-generic
  Architecture: x86_64

**Comment by nilmerg** [comment]
Hi, thanks, already found the issue and fixed it.

**Comment by MarcusCaepio** [comment]
Thanks @nilmerg for the quick fix. When will the packages be available?

**Comment by nilmerg** [comment]
Soon. Though, there's currently a gremlin on the build system. :roll_eyes:

**Comment by dnsmichi** [comment]
I've removed the Gremlin ;)

**Comment by MarcusCaepio** [comment]
Thanks for the quick fix!
