### ISSUE TITLE
Reschedule multiple checks gives error "The filter column "service_active_checks_enabled" is not allowed here"

### ISSUE THREAD

**Issue by lukastopiarz** [Icinga/icingaweb2#4001]
Hello.
I have encountered a problem when trying to reschedule a check on multiple services today.  
Icingaweb reports ``"The filter column "service_active_checks_enabled" is not allowed here"``
```
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(455): Icinga\Module\Monitoring\DataView\DataView->validateFilterColumns(Object(Icinga\Data\Filter\FilterMatch))
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(455): Icinga\Module\Monitoring\DataView\DataView->validateFilterColumns(Object(Icinga\Data\Filter\FilterMatch))
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(430): Icinga\Module\Monitoring\DataView\DataView->validateFilterColumns(Object(Icinga\Data\Filter\FilterAnd))
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Object/ServiceList.php(167): Icinga\Module\Monitoring\DataView\DataView->applyFilter(Object(Icinga\Data\Filter\FilterAnd))
#4 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/services/show.phtml(13): Icinga\Module\Monitoring\Object\ServiceList->getScheduledDowntimes()
#5 /usr/share/php/Icinga/Web/View.php(262): include(String)
#6 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#12 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#14 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#16 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#17 {main}
```

## Reproduce
1) Select multiple active services (2 and more)
2) Click on "reschedule"
3) Click on "Schedule checks"

## Screenshots

![Screenshot 2019-11-19 at 08 50 17](https://user-images.githubusercontent.com/15138454/69128596-f89e5480-0aac-11ea-9085-ccb1530de1ab.png)

![Screenshot 2019-11-19 at 08 49 46](https://user-images.githubusercontent.com/15138454/69128601-fe943580-0aac-11ea-80c6-55ee5ffe2c92.png)

## Environment:
Icingaweb2 2.7.3
Icinga2 2.11.2
php 7.1
Centos 7.7

What is the problem, please?

**Comment by nilmerg** [comment]
Hi,

thanks for the report! The problem is that the redirect adds an invalid filter column to the url.

So it's only the final redirect after the rescheduling has been performed. Just remove `&service_active_checks_enabled=1` from the url in the address bar and you'll get the view prior to the form submission.

**Comment by lukastopiarz** [comment]
Hello and thanks for the feedback!
Yes, I confirm that erasing ``&service_active_checks_enabled=1`` from url returns a list with services.
