### ISSUE TITLE
SQL error when retrieving service history after upgrade

### ISSUE THREAD

**Issue by XANi** [Icinga/icingaweb2#4116]
After upgrading to 2.11.3-1-buster/ 2.7.3-1.buster (latest stable packages of icinga/icingaweb2 for buster) we get 

SQLSTATE[42803]: Grouping error: 7 ERROR: column "hn.start_time" must appear in the GROUP BY clause or be used in an aggregate function

after clicking history tab.

other software:
* Debian Buster 
* PostgreSQL11.6
* PHP7.0/PHP7.3 (tried both)

Here is the query from postgresql logs: [icingaweb2_query.txt](https://github.com/Icinga/icingaweb2/files/4404053/icingaweb2_query.txt). 

and here is the stack trace:
```
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Select.php(705): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#4 /usr/share/php/Icinga/Data/Db/DbConnection.php(100): Zend_Db_Select->query()
#5 /usr/share/php/Icinga/Data/SimpleQuery.php(171): Icinga\Data\Db\DbConnection->query(Object(Icinga\Module\Monitoring\Backend\Ido\Query\EventhistoryQuery))
#6 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/event-history.phtml(38): Icinga\Data\SimpleQuery->rewind()
#7 /usr/share/php/Icinga/Web/View.php(262): include(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#9 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/object/detail-history.phtml(13): Zend_View_Abstract->render(NULL)
#10 /usr/share/php/Icinga/Web/View.php(262): include(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(206): Zend_Controller_Action_Helper_ViewRenderer->render(String, NULL, Boolean)
#15 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(117): Zend_Controller_Action->render(String, NULL, Boolean)
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->historyAction()
#17 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#22 {main}

SQLSTATE[42803]: Grouping error: 7 ERROR: column "hn.start_time" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ... (SELECT hn.notification_id AS id, UNIX_TIMESTAMP(hn.start_t...
^

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php(219): PDOStatement->execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#4 /usr/share/icingaweb2/library/vendor/Zend/Db/Select.php(705): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /usr/share/php/Icinga/Data/Db/DbConnection.php(100): Zend_Db_Select->query()
#6 /usr/share/php/Icinga/Data/SimpleQuery.php(171): Icinga\Data\Db\DbConnection->query(Object(Icinga\Module\Monitoring\Backend\Ido\Query\EventhistoryQuery))
#7 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/event-history.phtml(38): Icinga\Data\SimpleQuery->rewind()
#8 /usr/share/php/Icinga/Web/View.php(262): include(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#10 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/object/detail-history.phtml(13): Zend_View_Abstract->render(NULL)
#11 /usr/share/php/Icinga/Web/View.php(262): include(String)
#12 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(206): Zend_Controller_Action_Helper_ViewRenderer->render(String, NULL, Boolean)
#16 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(117): Zend_Controller_Action->render(String, NULL, Boolean)
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->historyAction()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#23 {main}
```

**Comment by nilmerg** [comment]
Hi,

I can't reproduce this with Postgres v12.2 and the current master of Web 2. Please answer me the following so that I can isolate it better:

- Which version of Icinga Web 2 did you use previously? (When it still worked)
- Does this happen for all services or just a few?

**Comment by XANi** [comment]
upgrade path was:
* icinga2 2.10.5  -> 2.11.3
* icingaweb 2.7.1 -> 2.7.3
* postgresql 9.6 -> 11.6
* php7.0->7.3
( basically upgrading "everything stretch"  to "everything buster")

The procedure was pretty much "dump DB, upgrade everything, restore DB".

But I think I now know what happened, I had other node (cluster of 2) running (and writing) during the import by accident and because of that some of the constraints were not applied correctly.

I still don't really get why that generated 86-line long query in icingaweb tho...
