### ISSUE TITLE
Update icingaweb2 from v2.7.3 to icingaweb2 v2.8.0

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2#4175]
## Describe the bug
When updating icingaweb2 to version 2.8.0 there are problems with the start of icinga2-director and other icinga2 modules.

## To Reproduce
At least these icinga2 modules should be installed.

1. vspheredb (v1.1.0)
2. incubator (v0.5.0)
3. reactbundle (v0.7.0)
4. ipl (v0.5.0)

## Expected behavior
After the update of icingaweb2 should everything work and no icinga2 modules should prevent this. Especially the essential module icinga director

## Screenshots
![grafik](https://user-images.githubusercontent.com/23358770/84128543-03b4d400-aa41-11ea-8f87-1577b209cb33.png)

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Firefox 68.9.0esr (64-Bit)
* icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.3-1)
* rh-php71 (7.1.30)
* RHEL 7.8

## Additional context
Some output from systemctl and journalctl 

```
]# systemctl restart icinga-director.service
Job for icinga-director.service failed because the control process exited with error code. See "systemctl status icinga-director.service" and "journalctl -xe" for details.

]# journalctl -xe
-- Subject: Unit icinga-vspheredb.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit icinga-vspheredb.service has begun starting up.
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: PHP Fatal error:  Uncaught Error: Call to undefined function Icinga\Module\Vspheredb\Daemon\posix_getpid() in /usr/share/ic
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: Stack trace:
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #0 /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php(57): Icinga\Module\Vspheredb\Daemon\Daemon->
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #1 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/DaemonCommand.php(25): Icinga\Module\Vspheredb\Daemon\Da
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #2 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Vspheredb\Clicommands\DaemonCommand->runAction()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #3 /usr/share/php/Icinga/Application/Cli.php(162): Icinga\Cli\Loader->dispatch()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #4 /usr/share/php/Icinga/Application/Cli.php(152): Icinga\Application\Cli->dispatchOnce()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #5 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #6 {main}
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: thrown in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php on line 64
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: Fatal error: Uncaught Error: Call to undefined function Icinga\Module\Vspheredb\Daemon\posix_getpid() in /usr/share/icingaw
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: Stack trace:
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #0 /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php(57): Icinga\Module\Vspheredb\Daemon\Daemon->
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #1 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/DaemonCommand.php(25): Icinga\Module\Vspheredb\Daemon\Da
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #2 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\Vspheredb\Clicommands\DaemonCommand->runAction()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #3 /usr/share/php/Icinga/Application/Cli.php(162): Icinga\Cli\Loader->dispatch()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #4 /usr/share/php/Icinga/Application/Cli.php(152): Icinga\Application\Cli->dispatchOnce()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #5 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: #6 {main}
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx icingacli[5392]: thrown in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/Daemon.php on line 64
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx systemd[1]: icinga-vspheredb.service: main process exited, code=exited, status=255/n/a
Jun 09 10:25:22 xxxxxxxxxxxxxxxxx systemd[1]: Failed to start Icinga vSphereDB Daemon.
-- Subject: Unit icinga-vspheredb.service has failed
```

After disabling the icinga module vspheredb

```
]# systemctl restart icinga-director.service
Job for icinga-director.service failed because the control process exited with error code. See "systemctl status icinga-director.service" and "journalctl -xe" for details.

]# journalctl -xe
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx polkitd[879]: Registered Authentication Agent for unix-process:9494:502160 (system bus name :1.144 [/usr/bin/pkttyagent --notify-fd 5 --fall
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx systemd[1]: Stopped Icinga Director - Monitoring Configuration.
-- Subject: Unit icinga-director.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit icinga-director.service has finished shutting down.
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx systemd[1]: Starting Icinga Director - Monitoring Configuration...
-- Subject: Unit icinga-director.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit icinga-director.service has begun starting up.
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: Started by systemd, notifying watchdog every 5s via /run/systemd/notify
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() in /usr/share/icingaweb2/modules/incubator
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: Stack trace:
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(74): gipfl\SystemD\NotifySystem
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(52): Icinga\Module\Director\Dae
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #2 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\D
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(181): React\EventLoop\Ti
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #4 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSele
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #5 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Direc in /usr/s
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx systemd[1]: icinga-director.service: main process exited, code=exited, status=255/n/a
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: Fatal error: Uncaught Error: Call to undefined function posix_getpid() in /usr/share/icingaweb2/modules/incubator/vend
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: Stack trace:
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(74): gipfl\SystemD\NotifySystem
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(52): Icinga\Module\Director\Dae
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #2 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\D
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(181): React\EventLoop\Ti
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #4 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSele
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx icingadirector[9500]: #5 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Direc in /usr/s
Jun 09 10:30:06 xxxxxxxxxxxxxxxxx systemd[1]: Failed to start Icinga Director - Monitoring Configuration.
-- Subject: Unit icinga-director.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit icinga-director.service has failed.
```

**Comment by nilmerg** [comment]
Hi,

we've changed the required PHP version on RHEL/CentOS 7+8 to v7.3. This is also covered in the [upgrading documentation](https://github.com/Icinga/icingaweb2/blob/master/doc/80-Upgrading.md#upgrading-to-icinga-web-2-28x). You'll need to install all of the php modules required for these modules for PHP 7.3 as well.

**Comment by akqopensystems** [comment]
It works now. Thanks for the hint :-)
