### ISSUE TITLE
PDF creation fails (for example Host overview)

### ISSUE THREAD

**Issue by Pio84** [Icinga/icingaweb2#4290]
## Describe the bug
Its not possible the create a PDF out of the icingaweb2 page.

## To Reproduce
Click on overview for exapmle Hosts, click on arrow down on top of the page and then the pdf button. Wait abaout 10 sec. and get the error: Source file could not be read.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

- Ubuntu 18.04.5 LTS
- Apache/2.4.29 (Ubuntu)
- PHP 7.3.23-4
- icinga2 version: r2.12.1-1
- icingaweb2 version 2.8.2
- Web browser used: FF 83.0 (64-Bit) and Vivaldi 3.2.1967.47 (Stable channel) (64-Bit)

## Additional context
Ubuntu Syslog:
Oct 27 13:32:04 MONITORING icingaweb2[97630]:
ErrorException in **/usr/share/php/Icinga/Web/Session/Php72Session.php:20** with message: **session_name()**: Cannot change session name when headers already sent
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Web/Session/Php72Session.php(20): session_name(String)
#2 /usr/share/php/Icinga/Web/Session/PhpSession.php(167): Icinga\Web\Session\Php72Session->open()
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(536): Icinga\Web\Session\PhpSession->write()
#4 /usr/share/php/Icinga/Web/Controller/ActionController.php(478): Icinga\Web\Controller\ActionController->shutdownSession()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(512): Icinga\Web\Controller\ActionController->postDispatch()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}

Some link i found: https://bugs.php.net/bug.php?id=75650&thanks=2
i have other icingaweb2 instances with older versions of icinga, there is no problem here.

**Comment by Al2Klimov** [comment]
Hello @Pio84 and thank you for reporting!

Unfortunately I couldn’t reproduce this with PHP 7.3. Please provide more detailed instructions.

Best,
AK

**Comment by Pio84** [comment]
> 
> 
> Hello @Pio84 and thank you for reporting!
> 
> Unfortunately I couldn’t reproduce this with PHP 7.3. Please provide more detailed instructions.
> 
> Best,
> AK

Hi  Al2Klimov,
what additional information do you need? I have set up three icinga systems since october, all of which have the problem. which versions did you use?

Regards,
Pio

**Comment by Pio84** [comment]
Hi @Al2Klimov 
what additional information do you need?

**Comment by Pio84** [comment]
![2020-12-17 09_07_37-Servicegruppen __ Icinga Web](https://user-images.githubusercontent.com/48513287/102460966-00ca1a00-4048-11eb-9744-f5b6ab7d8fa9.png)
![2020-12-17 09_13_47-icinga@monitoring01_ ~](https://user-images.githubusercontent.com/48513287/102461200-5b637600-4048-11eb-9583-2c978d6865ef.png)

**Web browser used:** 
FF 83.0 (64-Bit)
**Icinga Web 2 Version**
2.8.2
**Git Commit**
8a89839af94a247ee2149b2336c73b8251b477c0
**PHP-Version**
7.3.24-3+ubuntu18.04.1+deb.sury.org+1
**Git Commit Datum**
2020-08-17

**Comment by Pio84** [comment]
![2020-12-17 09_07_37-Servicegruppen __ Icinga Web](https://user-images.githubusercontent.com/48513287/102460966-00ca1a00-4048-11eb-9744-f5b6ab7d8fa9.png)
![2020-12-17 09_13_47-icinga@monitoring01_ ~](https://user-images.githubusercontent.com/48513287/102461200-5b637600-4048-11eb-9583-2c978d6865ef.png)

**Web browser used:** 
FF 83.0 (64-Bit)
**Icinga Web 2 Version**
2.8.2
**Git Commit**
8a89839af94a247ee2149b2336c73b8251b477c0
**PHP-Version**
7.3.24-3+ubuntu18.04.1+deb.sury.org+1
Git Commit Datum
2020-08-17

**Comment by Al2Klimov** [comment]
## Tasks

* Reproduce this one
* If successful, keep the VM

**Comment by Yonas-net** [comment]
I can't reproduce it either, unfortunately. [list-services-1610724979.pdf](https://github.com/Icinga/icingaweb2/files/5821431/list-services-1610724979.pdf)

**Comment by Zoetrap** [comment]
Hi,

Just chipping in on this.

I was experiencing the **exact** same problem as @Pio84 reported above. 
I had done a completely fresh install of Ubuntu Server 20.04 and installed Icinga2, no extra fussing around. PHP export did not wotk out of the box.

Specs:

Ubuntu 20.04 LTS
PHP 7.3.26-1
icinga2 version: r2.12.3-1
Icinga Web 2 Version 2.8.2

I am not a programmer, but I studied the stack trace in the apache2 error.log and actually managed to get the .pdf-export working by commenting out line 536 in /usr/share/php/Icinga/Web/Controller/ActionController.php like so:

```
protected function shutdownSession()
        $session = Session::getSession();
        if ($session->hasChanged()) {
**/*            $session->write();  */**
        }
    }
```
As I said I am not familiar with php and I have absolutely no idea if this breaks anything else down the line. So far everything _seems_ to be working.

But anyway, maybe this could at least be a pointer towards what the root problem could be regarding this seemingly elusive bug.

**Comment by nilmerg** [comment]
Hi Zoetrap,

no, that is far from a solution what you've changed there. You essentially disabled session storage for any other view/feature with this change. This might not break things at first look, but you'll experience weird behavior sooner or later for sure.

**Comment by Zoetrap** [comment]
Thanks for the info @nilmerg. It's definately not a hack I want to be using in that case.

I'll try to investigate this issue further. Hopefully I'll be able track something down.

**Comment by Zoetrap** [comment]
I don't know if the following an ideal solution either. I presume it leaves a session open. However, skipping this session shutdown under the function postDispatch() in the same file also allows the .pdf function to work without failure: 

```
        if ($req->getParam('error_handler') === null && $req->getParam('format') === 'pdf') {
            $this->sendAsPdf();
//          $this->shutdownSession();
            exit;
        }
```

I guess it's at least a bit better since this part of the function only gets called when you choose to generate a .pdf.
Dare I leave it like this or could there be complications with this as well?

**Comment by nilmerg** [comment]
Nope, as quick work-around this is far better. But still a work-around :wink:

**Comment by Al2Klimov** [comment]
What about swapping shutdownSession and sendAsPdf?

**Comment by Zoetrap** [comment]
@Al2Klimov I just tried that and it seems to work fine as well :)

```
        if ($req->getParam('error_handler') === null && $req->getParam('format') === 'pdf') {
            $this->shutdownSession();
            $this->sendAsPdf();
            exit;
        }

```

**Comment by Al2Klimov** [comment]
Feel free to open a PR.

**Comment by nilmerg** [comment]
I'm afraid, but the reason *it works* is not enough to open a PR. Not without an explanation *why* it works, at least. So please don't open a PR if you can't explain why it works.

**Comment by Al2Klimov** [comment]
Isn’t the reason obvious for you as web dev?

**Comment by Al2Klimov** [comment]
TL;DThink: shutdownSession seems to write headers, but this doesn’t work after sendAsPdf has written the body. Enough explanation?

**Comment by deubert-it** [comment]
This might also be related to a webserver or php configuration issue. Just from experience, this message: "Cannot change session name **when headers already sent**" could be something as:
- Specific notice/deprecation logging which is enabled on the system, which could generate noise before the Script executes
- Specific version or combination of php modules that is only present on your system, which might also generate output/noise
- Some other configuration that is set on the target system, which is not standard and might cause a similar output issue

This is usually hard to investigate without access to the system. In 99% of the cases I have seen, it was not related to the session or related call at all, as this is just a symptom.

What you could provide:
- How do you install/provision those systems? If there are specific php settings/modules installed in your versions, please provide documentation about that
- provide output of php -v, php -m and php -i
- check your php and apache logfiles for any other output that might happen directly before you see the ErrorException log entry

What you could test:
- Reinstall the system with distribution default php configuration and check if the error still exists. If no, this would be proof it is related to the used configuration/installed modules.

Workaround:
- Try to enable or increase output buffering, i.e. ```output_buffering=4096``` in your php configuration. This will not change functionality of the web application, but it has the chance to catch the output that is generated somewhere before the session code is executed, so it should work and would not need changes in application code.

**Comment by nilmerg** [comment]
Just tested pdfexport myself again, without the pdfexport module, and it works fine. So closing here since this collected enough dust as well.
