### ISSUE TITLE
Uncaught Error: Call to undefined function Icinga\Util\json_decode() in /usr/share/php/Icinga/Util/Json.php:88

### ISSUE THREAD

**Issue by marxin** [Icinga/icingaweb2#4307]
When I open icinga homepage I see the following exception:

```
Uncaught Error: Call to undefined function Icinga\Util\json_decode() in /usr/share/php/Icinga/Util/Json.php:88
Stack trace:
#0 /usr/share/php/Icinga/Web/ApplicationStateCookie.php(27): Icinga\Util\Json::decode()
#1 /usr/share/php/Icinga/Web/Widget/ApplicationStateMessages.php(20): Icinga\Web\ApplicationStateCookie->__construct()
#2 /usr/share/php/Icinga/Web/Widget/ApplicationStateMessages.php(45): Icinga\Web\Widget\ApplicationStateMessages->getMessages()
#3 /usr/share/php/Icinga/Web/Widget/AbstractWidget.php(114): Icinga\Web\Widget\ApplicationStateMessages->render()
#4 /usr/share/icingaweb2/application/controllers/ApplicationStateController.php(73): Icinga\Web\Widget\AbstractWidget->__toString()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\ApplicationStateController->summaryAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Contr

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

## Your Environment

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
2.8.2
Git commit
8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version
7.4.14
```

I use `openSUSE Tumbleweed`

**Comment by marxin** [comment]
Fixed by the installation of `php7-json` package (which removes `php8` package for now).
