### ISSUE TITLE
Uncaught Error: Call to undefined function mb_strlen() in /usr/share/icingaweb2/library/vendor/Parsedown/Parsedown.php:170

### ISSUE THREAD

**Issue by kaistian** [Icinga/icingaweb2#4327]
## Describe the bug
Added a comment to a service and get the following stacktrace
```
[Mon Mar 01 06:18:06.933672 2021] [php7:error] [pid 3553135] [client 110.2.0.70:43808] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /usr/share/icingaweb2/library/vendor/Parsedown/Parsedown.php:170
Stack trace:
  #0 /usr/share/icingaweb2/library/vendor/Parsedown/Parsedown.php(39): Parsedown->lines()
  #1 /usr/share/php/Icinga/Web/Helper/Markdown.php(20): Parsedown->text()
  #2 /usr/share/php/Icinga/Web/View/helpers/string.php(24): Icinga\\Web\\Helper\\Markdown::text()
  #3 [internal function]: Icinga\\Web\\View->Icinga\\Web\\View\\{closure}()
  #4 /usr/share/php/Icinga/Web/View.php(176): call_user_func_array()
  #5 /usr/share/php/Icinga/Web/View.php(262): Icinga\\Web\\View->callHelperFunction()
  #6 /usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/comments.phtml(71): Icinga\\Web\\View->__call()
  #7 /usr/share/php/Icinga/Web/View.php(248): include('/usr/share/icin...')
  #8 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\\Web\\View->_run()
  #9 /usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/object/detail-content.phtml(10): Zend_V in /usr/share/icingaweb2/library/vendor/Parsedown/Parsedown.php on line 170, referer: https://monitor.example.com/dashboard
```

## To Reproduce

I added the following string as a comment by pressing `Add comment` on a service and pasted the clipboard
```
752368-081      DIMM DDR4       8192 MB         2133 MHz        1.2 V   1       RDIMM
```
The exact content I pasted in
```
$ xclip -o | hexdump -C
00000000  37 35 32 33 36 38 2d 30  38 31 20 09 44 49 4d 4d  |752368-081 .DIMM|
00000010  20 44 44 52 34 20 09 38  31 39 32 20 4d 42 20 09  | DDR4 .8192 MB .|
00000020  32 31 33 33 20 4d 48 7a  20 09 31 2e 32 20 56 20  |2133 MHz .1.2 V |
00000030  09 31 20 09 52 44 49 4d  4d 20                    |.1 .RDIMM |
0000003a
```

## Your Environment
Icinga2 and Icingaweb2 is running on Ubuntu 20.04 with packages from `http://packages.icinga.com`
```
$ dpkg -l | egrep "\sicinga2\s|\sicingaweb2\s"
ii  icinga2              2.12.3-1.focal          amd64        host and network monitoring system
ii  icingaweb2           2.8.2-1.focal           all          simple and responsive web interface for Icinga

Loaded modules:
doc          v2.8.2
monitoring   v2.8.2

PHP is version 7.4.3

Database used is PostgreSQL 12.5

Client is Kubuntu 20.04 with Firefox 85
```

**Comment by nilmerg** [comment]
Hi,

you seem to be missing the `mbstring` php module. (https://icinga.com/docs/icinga-web-2/latest/doc/02-Installation/#installing-requirements)
Install/Enable this and this error should go away.

**Comment by kaistian** [comment]
Thanks, looking at my Ansible code looks like I forgot that one, added it and installed it and error went away.

Is there a reason why the php modules is not set as an dependency in the icingaweb2 deb packages?

**Comment by nilmerg** [comment]
Not a reason that I know of. Please open a bug report over at https://github.com/Icinga/icinga-packaging for this. Thank you!
