### ISSUE TITLE
Custom Variables with space(s) break Filter

### ISSUE THREAD

**Issue by abaumgaertner** [Icinga/icingaweb2#4342]
## Describe the bug
Custom Variables with space(s) in Name cause exception / stack trace in Filter.

## To Reproduce
Host
1. create host custom var with space in varname: e.g. message group
2. Filter in WebGUI /icingaweb2/monitoring/list/hosts?_host_Message%20Group=dummy&modifyFilter=1

Service
1. create service custom var with space in varname: e.g. message group
2. Filter in WebGUI /icingaweb2/monitoring/list/hosts?_service_Message%20Group=dummy&modifyFilter=1

## Expected behavior
Filtered Results

## Screenshots
Host
![grafik](https://user-images.githubusercontent.com/11097052/113573738-065d6700-961b-11eb-8f7f-ec11ef483fe4.png)
/icingaweb2/monitoring/list/hosts?_host_Message%20Group=dummy&modifyFilter=1
![grafik](https://user-images.githubusercontent.com/11097052/113574033-98fe0600-961b-11eb-8f66-594b11f859d3.png)
Got invalid custom var: "_host_message group"
````
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1191): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->customvarNameToTypeName(String)
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1178): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->joinCustomvar(String)
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1041): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireCustomvar(String)
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(683): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireColumn(String)
#4 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(772): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireFilterColumns(Object(Icinga\Data\Filter\FilterMatch))
#5 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(493): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->addFilter(Object(Icinga\Data\Filter\FilterMatch))
#6 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(432): Icinga\Module\Monitoring\DataView\DataView->addFilter(Object(Icinga\Data\Filter\FilterMatch))
#7 /usr/share/php/Icinga/Web/Widget/FilterEditor.php(350): Icinga\Module\Monitoring\DataView\DataView->applyFilter(Object(Icinga\Data\Filter\FilterMatch))
#8 /usr/share/php/Icinga/Web/Controller.php(254): Icinga\Web\Widget\FilterEditor->handleRequest(Object(Icinga\Web\Request))
#9 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(747): Icinga\Web\Controller->setupFilterControl(Object(Icinga\Module\Monitoring\DataView\HostStatus), NULL, NULL, Array)
#10 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(96): Icinga\Module\Monitoring\Controllers\ListController->filterQuery(Object(Icinga\Module\Monitoring\DataView\HostStatus))
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ListController->hostsAction()
#12 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#14 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#16 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#17 {main}
````
Service
![grafik](https://user-images.githubusercontent.com/11097052/113573713-f6458780-961a-11eb-89ee-23cc8f35e9d0.png)
/icingaweb2/monitoring/list/hosts?_service_Message%20Group=dummy&modifyFilter=1
![grafik](https://user-images.githubusercontent.com/11097052/113573903-563c2e00-961b-11eb-8b40-4946a5addb93.png)
Got invalid custom var: "_service_message group"
````
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1191): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->customvarNameToTypeName(String)
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1178): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->joinCustomvar(String)
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1041): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireCustomvar(String)
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(683): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireColumn(String)
#4 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(772): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireFilterColumns(Object(Icinga\Data\Filter\FilterMatch))
#5 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(493): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->addFilter(Object(Icinga\Data\Filter\FilterMatch))
#6 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(432): Icinga\Module\Monitoring\DataView\DataView->addFilter(Object(Icinga\Data\Filter\FilterMatch))
#7 /usr/share/php/Icinga/Web/Widget/FilterEditor.php(350): Icinga\Module\Monitoring\DataView\DataView->applyFilter(Object(Icinga\Data\Filter\FilterMatch))
#8 /usr/share/php/Icinga/Web/Controller.php(254): Icinga\Web\Widget\FilterEditor->handleRequest(Object(Icinga\Web\Request))
#9 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(747): Icinga\Web\Controller->setupFilterControl(Object(Icinga\Module\Monitoring\DataView\HostStatus), NULL, NULL, Array)
#10 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(96): Icinga\Module\Monitoring\Controllers\ListController->filterQuery(Object(Icinga\Module\Monitoring\DataView\HostStatus))
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ListController->hostsAction()
#12 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#14 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#16 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#17 {main}
````
## Your Environment

![grafik](https://user-images.githubusercontent.com/11097052/113574473-76202180-961c-11eb-9b21-1b443ad0873f.png)

* Browser: Google Chrome: Version 89.0.4389.72 (Offizieller Build) (64-Bit)

* Server operating system and version:
````
cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Oracle Linux Server 7.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.8
````

**Comment by abaumgaertner** [comment]
world record time bug fix :+1: thanks
