### ISSUE TITLE
Adding a user to groups is broken on 2.9.0

### ISSUE THREAD

**Issue by sircubbi** [Icinga/icingaweb2#4450]
After updating to icingaweb 2.9.0 it is no longer possible to assign groups to a user, using the functionality at
 Configuration -> Access Control -> Users.

When clicking on a specific user and then "Create New Membership", the following Exception is presented:
```
Uncaught Error: Call to undefined method ipl\Web\Widget\Tabs::showOnlyCloseButton() in /usr/share/icingaweb2/application/views/scripts/user/form.phtml:2
Stack trace:
#0 /usr/share/php/Icinga/Web/View.php(235): include()
#1 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('user/form.phtml', NULL)
#4 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(47): Zend_Controller_Action_Helper_ViewRenderer->render('form', NULL, false)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(206): ipl\Web\Compat\ViewRenderer->render('form', NULL, false)
#6 /usr/share/icingaweb2/application/controllers/UserController.php(262): Zend_Controller_Action->render('form'
```

This happens using to supplied RPM-packages on EL8. As far as I see the method `showOnlyCloseButton()` is defined in a different namespace (`Icinga` and not `ipl`).

**Comment by sircubbi** [comment]
I can confirm that the commit from #4451fixes the issue.
