### ISSUE TITLE
Debian upgrade icingaweb 2.8 to 2.9 php fatal error Locale not found

### ISSUE THREAD

**Issue by xseth** [Icinga/icingaweb2#4459]
Hi,

By updating via APT icingaweb2 I now have this error :

2021/07/17 10:26:39 [error] 27887#27887: *24 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class ‘Locale’ not found in /usr/share/icinga-php/ipl/vendor/ipl/i18n/src/Locale.php:122
Stack trace:
#0 /usr/share/icinga-php/ipl/vendor/ipl/i18n/src/Locale.php(87): ipl\I18n\Locale->parseLocale(‘fr_fr’)
#1 /usr/share/php/Icinga/Application/Web.php(514): ipl\I18n\Locale->getPreferred(‘fr-FR,fr;q=0.9,…’, Array)
#2 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(730): Icinga\Application\Web->detectLocale()
#3 /usr/share/php/Icinga/Application/Web.php(105): Icinga\Application\ApplicationBootstrap->setupInternationalization()
#4 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(416): Icinga\Application\Web->bootstrap()
#5 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\ApplicationBootstrap::start()
#6 /usr/share/icingaweb2/public/index.php(4): require_once(’/usr/share/php/…’)
#7 {main}

Icinga Web 2 version : 2.8 upgrade to 2.9
Web browser used : Brave
Icinga 2 version used (icinga2 --version) : r2.12.5-1
PHP version used (php --version) : 7.0
Server operating system and version Debian 9

**Comment by xseth** [comment]
I solved my problem by installing : php7.0-intl
