### ISSUE TITLE
Encoding error after Upgrade from 2.8.x to 2.9.x (utf8mb4)

### ISSUE THREAD

**Issue by gbrehmer** [Icinga/icingaweb2#4492]
## Describe the bug
Is remeberme Feature is activated, we got an error ("Invalid parameter value: 7 ERROR:  invalid value for parameter "client_encoding": "utf8mb4"") in the web ui after login:
(from logfile):
```
2021-07-28T07:52:30+02:00 - ERROR - PDOException in /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php:82 with message: SQLSTATE[22023]: Invalid parameter value: 7 ERROR:  invalid value for parameter "client_encoding": "utf8mb4"
#0 [internal function]: PDO->exec(String)
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(82): call_user_func_array(Array, Array)
#2 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(164): ipl\Sql\Connection->__call(String, Array)
#3 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(399): ipl\Sql\Connection->connect()
#4 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(438): ipl\Sql\Connection->prepexec(String)
#5 /usr/share/php/Icinga/Web/RememberMe.php(250): ipl\Sql\Connection->insert(String, Array)
#6 /usr/share/icingaweb2/application/forms/Authentication/LoginForm.php(142): Icinga\Web\RememberMe->persist()
#7 /usr/share/php/Icinga/Web/Form.php(1178): Icinga\Forms\Authentication\LoginForm->onSuccess()
#8 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(86): Icinga\Web\Form->handleRequest()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main
```
## To Reproduce
Login with "remeberme" checkbox checked
Frontend is fully usable If I go manually to the dashboard by changing the url

## Screenshots
![image](https://user-images.githubusercontent.com/1201680/127319540-432c9686-21d2-4621-8bb1-3b868f87b242.png)

## Your Environment

* Icinga Web 2 version and modules (System - About):  2.9.1
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): r2.12.5-1
* PHP version used (`php --version`): 7.3.29-1~deb10u1
* Server operating system and version: Debian 10
* Postgresql: all databases have UTF8 encoding

## Unsuccessful changes

* set `utf8`, `UTF8` as `charset` in `resources.ini` (default value was previously used = not set)

**Comment by gbrehmer** [comment]
postgres db overview:
```
                                  List of databases
    Name    |  Owner   | Encoding |  Collate   |   Ctype    |    Access privileges
------------+----------+----------+------------+------------+-------------------------
 grafana    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =T/postgres            +
            |          |          |            |            | postgres=CTc/postgres  +
            |          |          |            |            | grafana=CTc/postgres
 icinga2    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =T/postgres            +
            |          |          |            |            | postgres=CTc/postgres  +
            |          |          |            |            | icinga2=CTc/postgres
 icingaweb2 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =T/postgres            +
            |          |          |            |            | postgres=CTc/postgres  +
            |          |          |            |            | icingaweb2=CTc/postgres
 postgres   | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres            +
            |          |          |            |            | postgres=CTc/postgres
 template1  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres            +
            |          |          |            |            | postgres=CTc/postgres
```

**Comment by nilmerg** [comment]
There's a v2.9.2 already for this.

**Comment by gbrehmer** [comment]
ah sorry, searched only for `utf8mb4`, please ban all users which reports error-messages with screenshots only ;)

**Comment by nilmerg** [comment]
better than without code wraps :rofl: (see e.g. #1)
