### ISSUE TITLE
Theme change for session throws backtrace Uncaught Error: Call to a member function isChecked() on null in /usr/share/php/Icinga/Web/Form.php:1231

### ISSUE THREAD

**Issue by flohoff** [Icinga/icingaweb2#4748]
Icingaweb 2.10 upgrade from 2.9

Suddenly everybody has a default dark theme and changing it throws a backtrace:

```
Uncaught Error: Call to a member function isChecked() on null in /usr/share/php/Icinga/Web/Form.php:1231
Stack trace:
#0 /usr/share/icingaweb2/application/forms/PreferenceForm.php(442): Icinga\Web\Form->isSubmitted()
#1 /usr/share/php/Icinga/Web/Form.php(1175): Icinga\Forms\PreferenceForm->isSubmitted()
#2 /usr/share/icingaweb2/application/controllers/AccountController.php(78): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AccountController->indexAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#6 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
thr
```

From looking the submit button has changed name - Its not btn_submit but btn_submit_session

Flo

**Comment by nilmerg** [comment]
Hi,

this occurs because you don't have a *User Preference Storage Type* configured. This is [deprecated](https://github.com/Icinga/icingaweb2/blob/master/doc/80-Upgrading.md#upgrading-to-icinga-web-2-29x) since v2.9.0. Please configure a database as *User Preference Storage Type* in the general configuration and this error is gone.

**Comment by nilmerg** [comment]
Duplicate of #4618
