### ISSUE TITLE
Invalid text representation: 7 ERROR: invalid input value for enum comment_type: "Ack"

### ISSUE THREAD

**Issue by sebastic** [Icinga/icingaweb2#4858]
## Describe the bug
Several pages show an exception when enabling the preview in Icinga DB.

This one is on several packages:
```
environment_id should be a resource got string instead

#0 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Contract/PropertyBehavior.php(63): ipl\Orm\Behavior\Binary->fromDb()
#1 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Behaviors.php(120): ipl\Orm\Contract\PropertyBehavior->retrieveProperty()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Redis/VolatileStateResults.php(131): ipl\Orm\Behaviors->retrieveProperty()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Redis/VolatileStateResults.php(79): Icinga\Module\Icingadb\Redis\VolatileStateResults->applyRedisUpdates()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/BaseItemList.php(87): Icinga\Module\Icingadb\Redis\VolatileStateResults->rewind()
#5 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/ItemList/StateList.php(23): Icinga\Module\Icingadb\Common\BaseItemList->assemble()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Icingadb\Widget\ItemList\StateList->assemble()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(497): ipl\Html\HtmlDocument->ensureAssembled()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\HtmlDocument->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#17 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(491): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#20 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#21 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#23 {main}
```

This one was only encountered on the Overdue page:
```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input value for enum comment_type: "Ack"
CONTEXT: unnamed portal parameter $1 = '...'

#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(402): PDOStatement->execute()
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(418): ipl\Sql\Connection->prepexec()
#2 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(656): ipl\Sql\Connection->select()
#3 /usr/share/icingaweb2/modules/icingadb/application/controllers/CommentsController.php(95): ipl\Orm\Query->count()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(477): Icinga\Module\Icingadb\Controllers\CommentsController->indexAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#7 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#8 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#10 {main}
```

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Install and configure icinga2, icingaweb2, icingadb, and icingadb-web
2. Visit pages in Icinga Web 2 and enable preview in Icinga DB

## Expected behavior
No exceptions are shown.

## Screenshots
![icingaweb2-current-incidents](https://user-images.githubusercontent.com/4605306/177035587-161dd84c-3638-4de6-b360-20c7112cb6b6.png)
![icingaweb2-dashboard-overdue](https://user-images.githubusercontent.com/4605306/177035588-67ce040a-cfeb-43c2-8480-4084863c6d73.png)
![icingaweb2-hostgroups](https://user-images.githubusercontent.com/4605306/177035590-c413ea3f-9349-4c2a-8a30-fa997047291e.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
  ```
  Icinga Web 2 Version           2.11.0
  PHP Version                    8.1.5
  ```
  **Loaded Libraries**
  ````
  icinga/icinga-php-thirdparty   0.11.0
  icinga/icinga-php-library      0.9.0
  ````
  **Loaded Modules**
  ```
  doc                            2.11.0
  icingadb                       1.0.0
  monitoring                     2.11.0
  ```
* Web browser used: Firefox 91.11.0esr (64-bit)
* Icinga 2 version used (`icinga2 --version`): 
   ```
   icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)

   Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
   License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
   This is free software: you are free to change and redistribute it.
   There is NO WARRANTY, to the extent permitted by law.

   System information:
     Platform: Debian GNU/Linux
     Platform version: Unknown
     Kernel: Linux
     Kernel version: 5.18.0-2-amd64
     Architecture: x86_64

   Build information:
     Compiler: GNU 11.3.0
     Build host: x86-csail-01
     OpenSSL version: OpenSSL 3.0.4 21 Jun 2022

   Application information:

   General paths:
     Config directory: /etc/icinga2
     Data directory: /var/lib/icinga2
     Log directory: /var/log/icinga2
     Cache directory: /var/cache/icinga2
     Spool directory: /var/spool/icinga2
     Run directory: /run/icinga2

   Old paths (deprecated):
     Installation root: /usr
     Sysconf directory: /etc
     Run directory (base): /run
     Local state directory: /var

   Internal paths:
     Package data directory: /usr/share/icinga2
     State path: /var/lib/icinga2/icinga2.state
     Modified attributes path: /var/lib/icinga2/modified-attributes.conf
     Objects path: /var/cache/icinga2/icinga2.debug
     Vars path: /var/cache/icinga2/icinga2.vars
     PID path: /run/icinga2/icinga2.pid
   ```
* PHP version used (`php --version`):
   ```
   PHP 8.1.5 (cli) (built: May 16 2022 17:15:25) (NTS)
   Copyright (c) The PHP Group
   Zend Engine v4.1.5, Copyright (c) Zend Technologies
       with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies
   ```
* Server operating system and version: Debian unstable amd64

## Additional context
Redis and PostgreSQL databases on localhost.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Please see the following issue and linked PR for a fix:

Icinga/ipl-orm#69

All the best,
Eric

**Comment by sebastic** [comment]
Thanks for the pointer, I've add the changes from that PR as patch to the Debian package.

That just leaves the `SQLSTATE` error on the Overdue page.

**Comment by nilmerg** [comment]
Duplicate of #4853

**Comment by nilmerg** [comment]
Have you really used the final state of the fix? I've updated it yesterday for this very reason.

**Comment by sebastic** [comment]
Yes. `wget https://github.com/Icinga/icingaweb2/pull/4854.patch` was used after the PR was merged.

https://salsa.debian.org/nagios-team/pkg-icingaweb2/-/blob/master/debian/patches/pr4854-Fix-incorrect-history-time-and-date.patch

Were any related changes in icinga-php-library or icinga-php-thirdparty required?

The only change since 2.11.0 on the master branch not included as a patch in the Debian package is f84057fd8384bf0ea7f820686615ed5a388e00f0, which seems unrelated.

**Comment by nilmerg** [comment]
Ah, now I get it. The same error happened here (which is fixed) but the one you showed is from Icinga DB Web.
