### ISSUE TITLE
Cannot load resource config "icinga_ido". Resource does not exist

### ISSUE THREAD

**Issue by li9270** [Icinga/icingaweb2#4877]
I install icinga2, mysql, icingaweb2, php, icingadb-redis.
setup icignaweb2, then login in it.
while the error is:
```
Cannot load resource config "icinga_ido". Resource does not exist
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(208): Icinga\Data\ResourceFactory::getResourceConfig()
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(287): Icinga\Module\Monitoring\Backend\MonitoringBackend->getResource()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(55): Icinga\Module\Monitoring\Backend\MonitoringBackend->query()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(242): Icinga\Module\Monitoring\DataView\DataView->__construct()
#4 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(85): Icinga\Module\Monitoring\Backend\MonitoringBackend->from()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ListController->hostsAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#8 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#9 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```
![屏幕截图 2022-07-15 152507](https://user-images.githubusercontent.com/61036958/179176390-be9e87ad-bdfc-44b9-997b-3dc577d75f54.png)
Anyone has met the issue? Or I forget some steps? Thanks a lot!

```
  os: Ubuntu 20.04.4 LTS
  icinga2 version: 
icingna2 r2.13.4-1
php v7.4.3
Icinga Web 2 Version 	2.11.1
Git commit 	eecf8d9934cbf30ec063cea4a525b26bfd2bf99a
PHP Version 	7.4.3
Git commit date 	2022-07-06
Loaded Libraries
icinga/icinga-php-library 	0.9.1
icinga/icinga-php-thirdparty 	0.11.0
Loaded Modules
doc 		2.11.1
icingadb 		1.0.0
migrate 		2.11.1
monitoring 		2.11.1
test 		2.11.1


~$ sudo icinga2 feature list 
Disabled features: compatlog elasticsearch gelf graphite influxdb influxdb2 livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command debuglog icingadb ido-mysql mainlog notification
```

**Comment by li9270** [comment]
The web wizard, 
the final output is: 
```
icingaweb2 setup
Successfully connected to existing database "icingaweb2"...
Creating database schema...
Login "icingaweb2" already exists...
Required privileges were already granted to login "icingaweb2".
The database has been fully set up!

General configuration has been successfully written to: /etc/icingaweb2/config.ini

Authentication configuration has been successfully written to: /etc/icingaweb2/authentication.ini
Account "admin" has been successfully created.
Account "admin" has been successfully defined as initial administrator.

User Group Backend configuration has been successfully written to: /etc/icingaweb2/groups.ini
User Group "Administrators" has been successfully created.
Account "admin" has been successfully added as member to user group "Administrators".

Resource configuration has been successfully written to: /etc/icingaweb2/resources.ini

Resource configuration update successful: /etc/icingaweb2/resources.ini

Module configuration update successful: /etc/icingaweb2/modules/icingab/config.ini

Commandtransport configuration update successful: /etc/icingaweb2/modules/icingadb/commandtransports.ini

Module "icingadb" has been successfully enabled.
```

**Comment by nilmerg** [comment]
What your screenshot shows is a view of the module `monitoring`. The wizard only enabled module `icingadb`. That's the reason for this error, as the module `monitoring` isn't configured at all.

If you only want to use Icinga DB, you don't need the `monitoring` module.

**Comment by li9270** [comment]
I want to monitor my device and host status on the web page.
I am new to icinga2，I need to manual configuration icingaweb2？Or install icinga director to config it？
Is there some example that I can follow? thanks a lot!

I disable the module monitoring by 'icingacli module disable monitoring'
the output is:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icinga.host' doesn't exist
#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(401): PDO->prepare()
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(418): ipl\Sql\Connection->prepexec()
#2 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(642): ipl\Sql\Connection->select()
#3 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(142): ipl\Orm\Query->yieldResults()
#4 [internal function]: ipl\Orm\ResultSet->yieldTraversable()
#5 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(122): Generator->valid()
#6 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(69): ipl\Orm\ResultSet->advance()
#7 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(614): ipl\Orm\ResultSet->current()
#8 /usr/share/icingaweb2/modules/icingadb/application/controllers/HostsController.php(124): ipl\Orm\Query->first()
#9 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(477): Icinga\Module\Icingadb\Controllers\HostsController->indexAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#13 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}
```

**Comment by nilmerg** [comment]
For general questions and guidance please head over to our forums: https://community.icinga.com/

> I disable the module monitoring by 'icingacli module disable monitoring' the output is:

This means the Icinga DB database schema isn't correctly set up. If you need further help with this, please also ask on the forums for help.
