### ISSUE TITLE
"Operation on an invalid type" in CSS

### ISSUE THREAD

**Issue by davidc** [Icinga/icingaweb2#4915]
## Describe the bug
After upgrading icingaweb2 to 2.11.1-1.buster today (using the Icinga package repository), all web pages are corrupted. Viewing the source of the CSS file reveals `Operation on an invalid type`.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Debian 10.13 with all updates
2. Icinga from Icinga apt repository with all updates

## Expected behavior
Not broken CSS.

## Screenshots

Full source of icinga.min.css:

```
Operation on an invalid type
#0 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Expression.php(51): Less_Tree_Operation->compile(Object(Less_Environment))
#1 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Call.php(44): Less_Tree_Expression->compile(Object(Less_Environment))
#2 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Expression.php(51): Less_Tree_Call->compile(Object(Less_Environment))
#3 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Value.php(26): Less_Tree_Expression->compile(Object(Less_Environment))
#4 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Rule.php(73): Less_Tree_Value->compile(Object(Less_Environment))
#5 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Rule->compile(Object(Less_Environment))
#6 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile(Object(Less_Environment))
#7 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php(185): Less_Tree_Ruleset->compile(Object(Less_Environment))
#8 /usr/share/icingaweb2/library/vendor/lessphp/lessc.inc.php(130): Less_Parser->getCss()
#9 /usr/share/php/Icinga/Web/LessCompiler.php(230): lessc->compile('\n\n@font-face {\n...')
#10 /usr/share/php/Icinga/Web/StyleSheet.php(218): Icinga\Web\LessCompiler->render()
#11 /usr/share/php/Icinga/Web/StyleSheet.php(258): Icinga\Web\StyleSheet->render(true)
#12 /usr/share/php/Icinga/Application/webrouter.php(64): Icinga\Web\StyleSheet::send(true, false)
#13 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#14 {main}


.. 07143em;
     vertical-align: 0.05357em; }
   
   .fa-lg {
     font-size: 1.25em;
     line-height: 0.05em;
     vertical-align: -0.075em; }
   
   .fa-xl {
     font-size: 1.5em;
     line-height: 0.04167em;
     vertical-align: -0.125em; }
   
   .fa-2xl {
     font-size: 2em;
     line-height: 0.03125em;
     vertical-align: -0.1875em; }
   
   .fa-fw {
     text-align: center;
     width: 1.25em; }
   
   .fa-ul {
     list-style-type: none;
     margin-left: var(--fa-li-margin, 2.5em);
     padding-left: 0; }
     .fa-ul > li {
       position: relative; }
   
   .fa-li {
!!   left: calc(var(--fa-li-width, 2em) * -1);
     position: absolute;
     text-align: center;
     width: var(--fa-li-width, 2em);
     line-height: inherit; }
   
   .fa-border {
     border-color: var(--fa-border-color, #eee);
     border-radius: var(--fa-border-radius, 0.1em);
     border-style: var(--fa-border-style, solid);
     border-width: var(--fa-border-width, 0.08em);
     padding: var(--fa-border-padding, 0.2em 0.25em 0.15em); }
   
   .fa-pull-left {
     float: left;
     margin-right: var(--fa-pull-margin, 0.3em); }
   
   .fa-pull-
..
```

## Your Environment

```
root@netman01:/etc/icinga2# cat /etc/debian_version
10.13
root@netman01:/etc/icinga2# dpkg --list  | grep icinga
ii  icinga-l10n                          1.2.0-1.buster                        amd64        l10n (short for Localization) provides all translations available for Icinga.
ii  icinga-php-common                    1.0.0-1.buster                        all          Icinga PHP Common for Icinga Web 2
ii  icinga-php-library                   0.10.0-1+debian10                     amd64        Icinga PHP Library - IPL
ii  icinga-php-thirdparty                0.10.0-2.buster                       all          Icinga PHP Thirdparty for Icinga Web 2
ii  icinga2                              2.13.5-1.buster                       amd64        host and network monitoring system
ii  icinga2-bin                          2.13.5-1.buster                       amd64        host and network monitoring system - daemon
ii  icinga2-common                       2.13.5-1.buster                       all          host and network monitoring system - common files
ii  icinga2-doc                          2.13.5-1.buster                       all          host and network monitoring system - documentation
ii  icinga2-ido-mysql                    2.13.5-1.buster                       amd64        host and network monitoring system - MySQL support
ii  icinga2-slack-notifications          1.0.4                                 all          Icinga2 notification integration with slack
ii  icingacli                            2.10.1-1.buster                       all          simple CLI tool for Icingaweb2 and its modules
ii  icingaweb2                           2.10.1-1.buster                       all          simple and responsive web interface for Icinga
ii  icingaweb2-common                    2.10.1-1.buster                       all          simple and responsive web interface for Icinga - common files
ii  icingaweb2-module-doc                2.10.1-1.buster                       all          simple and responsive web interface for Icinga - documentation module
ii  icingaweb2-module-monitoring         2.10.1-1.buster                       all          simple and responsive web interface for Icinga - monitoring module
ii  php-icinga                           2.10.1-1.buster                       all          PHP library to communicate with and use Icinga
root@netman01:/etc/icinga2# php --version
PHP 7.3.31-1~deb10u1 (cli) (built: Oct 24 2021 15:18:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.31, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.31-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
root@netman01:/etc/icinga2#

```

**Comment by nilmerg** [comment]
Hi, please upgrade Icinga Web 2 to v2.10.3

**Comment by davidc** [comment]
Thank you and sorry, the package had been held back for some reason.

```
root@netman01:~# apt update; apt upgrade
Hit:2 http://security.debian.org buster/updates InRelease
Hit:1 https://packages.icinga.com/debian icinga-buster InRelease
Hit:3 http://debian.mirror.uk.sargasso.net/debian buster-updates InRelease
Hit:4 http://debian.mirror.uk.sargasso.net/debian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  icinga-php-thirdparty icingacli icingaweb2 icingaweb2-common icingaweb2-module-doc
  icingaweb2-module-monitoring php-icinga
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
root@netman01:~# apt install icingaweb2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  icinga-php-thirdparty icingacli icingaweb2-common icingaweb2-module-doc
  icingaweb2-module-monitoring php-icinga
The following packages will be upgraded:
  icinga-php-thirdparty icingacli icingaweb2 icingaweb2-common icingaweb2-module-doc
  icingaweb2-module-monitoring php-icinga
7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 9,371 kB of archives.
After this operation, 772 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```
