### ISSUE TITLE
Icinga Director Error

### ISSUE THREAD

**Issue by jeroatk** [Icinga/icingaweb2#4935]
## Describe the bug
Icinga Director web interface is not working. 

## To Reproduce
Uncaught Error: Class 'Icinga\Util\Translator' not found in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Translator.php:20
Stack trace:
#0 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/translation/src/TranslationHelper.php(17): gipfl\IcingaWeb2\Translator->translate('Overview')
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Tabs/MainTabs.php(26): Icinga\Module\Director\Web\Tabs\MainTabs->translate('Overview')
#2 /usr/share/icingaweb2/modules/director/application/controllers/DashboardController.php(49): Icinga\Module\Director\Web\Tabs\MainTabs->__construct(Object(Icinga\Authentication\Auth), 'director_db')
#3 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(40): Icinga\Module\Director\Controllers\DashboardController->indexAction()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\IndexController->indexAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

## Screenshots
![kép](https://user-images.githubusercontent.com/116201991/196770093-451745c9-cb97-4273-9a76-224310446ae5.png)

## Your Environment
Icinga Web 2 Version 	2.11.1
Git commit 	eecf8d9934cbf30ec063cea4a525b26bfd2bf99a
PHP Version 	7.3.33-7+ubuntu20.04.1+deb.sury.org+2
Git commit date 	2022-07-06
Loaded Libraries
icinga/icinga-php-thirdparty 	0.11.0
icinga/icinga-php-library 	0.10.0
Loaded Modules
director 		1.7.2 	
doc 		2.11.1 	
incubator 		0.5.0 	
ipl 		v0.5.0 	
monitoring 		2.11.1 	
reactbundle 		0.8.0

**Comment by Thomas-Gelf** [comment]
As you upgraded Icinga Web 2, you need a newer version of the Incubator module. v0.5.0 is installed, v0.19.0 is available
