### ISSUE TITLE
Update to 2.11.3 throws errors

### ISSUE THREAD

**Issue by mzac** [Icinga/icingaweb2#4966]
## Describe the bug
Upgraded to 2.11.3 and can no longer access the UI.  Getting errors in apache logs

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Upgrade to 2.11.3
2. Login to web interface

## Expected behavior
It should work and not throw an error

## Screenshots
![image](https://user-images.githubusercontent.com/10270879/207644806-0050ab00-61a0-4672-93e5-99545dba6d0c.png)

## Log
```
==> icingaweb2-error.log <==
[Wed Dec 14 10:48:19.682854 2022] [proxy_fcgi:error] [pid 1596893] [client 192.168.0.1:52656] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: require_once(lessphp/lessc.inc.php): Failed to open stream: No such file or directory in /usr/share/php/Icinga/Util/LessParser.php:9\nStack trace:\n#0 /usr/share/php/Icinga/Util/LessParser.php(9): Icinga\\Application\\ApplicationBootstrap->Icinga\\Application\\{closure}()\n#1 /usr/share/php/Icinga/Util/LessParser.php(9): require_once()\n#2 /usr/share/php/Icinga/Application/ClassLoader.php(303): require('...')\n#3 /usr/share/php/Icinga/Web/LessCompiler.php(64): Icinga\\Application\\ClassLoader->loadClass()\n#4 /usr/share/php/Icinga/Web/StyleSheet.php(117): Icinga\\Web\\LessCompiler->__construct()\n#5 /usr/share/php/Icinga/Web/StyleSheet.php(251): Icinga\\Web\\StyleSheet->__construct()\n#6 /usr/share/php/Icinga/Application/webrouter.php(62): Icinga\\Web\\StyleSheet::send()\n#7 /usr/share/icingaweb2/public/index.php(4): require_once('...')\n#8 {main}\n  thrown in /usr/share/php/Icinga/Util/LessParser.php on line 9', referer: https://icinga.home.local/icingadb/hosts?host.state.is_problem=y&host.state.is_handled=n&sort=host.state.last_state_change%20desc
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.3-1.focal
* Web browser used: Chrome 108
* Icinga 2 version used (`icinga2 --version`): r2.13.6-1
* PHP version used (`php --version`): 8.1.13
* Server operating system and version: Ubuntu 20.04.5 LTS

**Comment by lippserd** [comment]
Yeah, I screwed that up badly 🙅.

Can you try this quickfix please?

`mv /usr/share/icingaweb2/library/vendor/vendor/* /usr/share/icingaweb2/library/vendor`

**Comment by mzac** [comment]
@lippserd Zend is already present in the parent dir and won't let me move it.

```
root@mon1:/var/log/apache2# mv /usr/share/icingaweb2/library/vendor/vendor/* /usr/share/icingaweb2/library/vendor
mv: cannot move '/usr/share/icingaweb2/library/vendor/vendor/Zend' to '/usr/share/icingaweb2/library/vendor/Zend': Directory not empty
```

**Comment by lippserd** [comment]
> Hmm, even though it threw an error it seems the gui is fixed now. But this still probably needs a new release to fix it.

Yeah sure!

**Comment by lippserd** [comment]
There is a new revision for each version released that should fix the problem.
