### ISSUE TITLE
Enabeling Administrative access for a Role throws exception

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4973]
## Describe the bug
Exception is thrown if i want to create a new Role and enbale "Administrative Access.
`
[Error](https://icinga.nisc.at/icingaweb2/role/add)
 
Uncaught Error: Call to undefined method Icinga\Authentication\RolesConfig::getOrder() in /usr/share/icingaweb2/library/vendor/Zend/Form.php:3390
Stack trace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(3296): Zend_Form->_sort()
#1 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(83): Zend_Form->rewind()
#2 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_FormElements->render()
#3 /usr/share/php/Icinga/Web/Form.php(1556): Zend_Form->render()
#4 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2990): Icinga\Web\Form->render()
#5 /usr/share/icingaweb2/application/views/scripts/simple-form.phtml(5): Zend_Form->__toString()
#6 /usr/share/php/Icinga/Web/View.php(235): include('/usr/share/icin...')
#7 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#9 /usr/share/icingaweb2/library/vendor/Z

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
`

## To Reproduce
see above
+ Exception is also thrown if you view a ROle with Administrative Access enabled

## Screenshots

![2023-01-09 10_49_14-Roles __ Icinga Web](https://user-images.githubusercontent.com/29682206/211280747-59874c11-7fdc-4084-a72d-c87bf86f2ddd.png)
![2023-01-09 10_49_04-Roles __ Icinga Web](https://user-images.githubusercontent.com/29682206/211280751-e3d6d8d1-ffe9-48dd-bc3b-abc4edc877c4.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 Version	2.11.3
* Icinga Web 2 Version	Ubuntu 20.04
* Git commit	f917436a894c1f4148a9c3d6a27f9c20f204e44f
* PHP Version	7.4.33
* Git commit date	2022-12-14
Loaded Libraries
* icinga/icinga-php-thirdparty	0.11.0
* icinga/icinga-php-library	0.10.1

**Comment by nilmerg** [comment]
Works fine for me. With a new role, with an existing one, and with one that has it already enabled.

**Comment by moreamazingnick** [comment]
I found the problem and it happens if you enbale a module named repository
steps to reproduce:
* create folder named repository in /usr/share/icingaweb2/modules
* enable the module repository
* create a new Role and enable "Administrative Access"
* exception
* disable the module repository
* rename module repository to info
* enable the module info
* no exception

**Comment by moreamazingnick** [comment]
sadly yes

**Comment by moreamazingnick** [comment]
maybe that helps:

If I call addElement() inside a Form, and want to name the element repository it produces the same error.

$this->addElement(
            'text',
            'repository',
            array(
                'description'   => $this->translate('Name of the Repository'),
                'label'         => $this->translate('Repository'),
                'placeholder'   => '',
                'required'      => true
            )
        );

**Comment by moreamazingnick** [comment]
more precisely a form that "extends Icinga\Forms\RepositoryForm; so the name of the field is not padded by anything

**Comment by moreamazingnick** [comment]
I think it is because Icinga\Forms\RepositoryForm has variable protected $repository, and it's the same with $mode $identifier, $data; which all cause an exception in $order = $this->{$key}->getOrder() if used in a RepositoryForm or as a module name
