### ISSUE TITLE
Getting error opening History "createTicketLinks() must be of the type string, null returned"

### ISSUE THREAD

**Issue by pbirokas** [Icinga/icingaweb2#5197]
## Describe the bug
When trying to open the history from some Services or Hosts, I am getting an error. Other work as expected

## To Reproduce
I have no idea!

## Expected behavior
Expected to see the history of all items.

## Screenshots
```
Return value of Icinga\Module\Icingadb\Widget\ItemList\BaseHistoryListItem::createTicketLinks() must be of the type string, null returned

#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/ItemList/BaseHistoryListItem.php(71): Icinga\Module\Icingadb\Widget\ItemList\BaseHistoryListItem->createTicketLinks(NULL)
#1 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/BaseListItem.php(65): Icinga\Module\Icingadb\Widget\ItemList\BaseHistoryListItem->assembleCaption(Object(ipl\Html\HtmlElement))
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/ListItemCommonLayout.php(23): ipl\Web\Common\BaseListItem->createCaption()
#3 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/BaseListItem.php(83): Icinga\Module\Icingadb\Widget\ItemList\HistoryListItem->assembleMain(Object(ipl\Html\HtmlElement))
#4 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/BaseListItem.php(142): ipl\Web\Common\BaseListItem->createMain()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(344): ipl\Web\Common\BaseListItem->assemble()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(566): ipl\Html\HtmlDocument->ensureAssembled()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#15 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#16 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\HtmlDocument->renderUnwrapped()
#17 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#18 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/Helper/ViewRenderer.php(970): ipl\Web\Compat\ViewRenderer->render()
#19 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#20 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(480): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#21 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#22 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#24 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#25 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#26 {main}
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.1
* Web browser used: Chrome  122.0.6261.112 
* Icinga 2 version used (`icinga2 --version`): r2.14.0-1
* PHP version used (`php --version`): PHP 7.2.24
* Server operating system and version: Rocky Linux release 8.9

**Comment by nilmerg** [comment]
Hi,

this is happening because you have a downtime event with no comment attached to it. (i.e. a downtime without a comment) This is actually not possible because it's required.

Have you migrated from IDO and the time you got this the list might have included an event before the migration?

**Comment by pbirokas** [comment]
We Setup this installation directly with icingadb.
So, there was no migration. 

You mean if a Downtime event in the database with comment, this may cause this error?
How can I Fix this? 
Is there another possibility then just redure retention on downtime?

**Comment by nilmerg** [comment]
I'm currently more interested in how this can occur :thinking: 

Please share the output of the following query while you're connected to the icingadb database:

```sql
SELECT h.downtime_history_id, dh.downtime_id
FROM history h
         LEFT JOIN downtime_history dh ON h.downtime_history_id = dh.downtime_id
WHERE h.event_type IN ('downtime_end', 'downtime_start')
  AND (h.downtime_history_id IS NULL OR dh.downtime_id IS NULL);
```

**Comment by pbirokas** [comment]
I got ~103K entries out of this query.

It looks like this:

```
downtime_history_id     downtime_id
£ÚJ¼Ô Ãÿ^X ^E^PN\0>¦<92><81>Èó  NULL
<91>ÍnM£<9d>¼)°<83>^QX<90>`|<9c>Y^T+÷   NULL
¥^\­xñ8&<84>B<93>^S^Yl<9c>¥ê0w¼ë        NULL
¡¤J¼4ñuµ^B^V¥<96>a^Q<82>&^[<93>^W`      NULL
J·Ã^U<95>U,¯^C¡<93>þ^Vv<86>JîÑ<93>¯     NULL
YÄ®¢°¢DO!¬>Lý^]^K¶ Eb^U NULL
Qá<8e>qbó^FÜÅëèë^^<89>?o\\]À`   NULL
<8a>§T^\¿0aÍµBîlªÕ l ø^WX       NULL
âC~G<92><8e><8a>ll<8d>AÐ Ì1<96>¥<91>`J  NULL
ièûnÿ0^H^Kä^LÄ-c^E^L[5FOR       NULL
Í8=ó­ê^Bl^Aýî  Äe%8VH<9c>       NULL
v^S<88><95>ÐKâ\n<8c>jÛ^?DØD<8b>£2"U     NULL
```

**Comment by nilmerg** [comment]
The `history` table in your database seems to miss vital constraints, which would disallow what you're experiencing: Missing entries in `downtime_history` referenced by entries in `history`.

Since the schema adds these constraints since 1.0.0-rc2 (i.e. since schema version 2), these should exist even if you've used Icinga DB v1.0.0-rc1. But I think this can safely be ruled out, since your schema table only includes an entry for version 3, which is v1.0.0 stable.

Though, this still doesn't explain why the constraints are missing. And, why Icinga DB doesn't insert accompanying entries in `downtime_history` or why they were deleted in case they ever existed.

I could suggest to remove the invalid entries in `history`, but I think that is only a temporary solution and doesn't prevent new invalid entries.

I'll transfer the issue to the Icinga DB repository, the folks there should be able to provide more insight.

In the meantime, please also tell us the database vendor plus version and whether you use a high-availability database cluster.
